-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv26_3AC : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001110101100";
    constant ap_const_lv26_135 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100110101";
    constant ap_const_lv24_FFFF85 : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110000101";
    constant ap_const_lv24_5D : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001011101";
    constant ap_const_lv26_145 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000101000101";
    constant ap_const_lv26_2B9 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010111001";
    constant ap_const_lv24_FFFFAC : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110101100";
    constant ap_const_lv26_1A3 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000110100011";
    constant ap_const_lv26_139 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000100111001";
    constant ap_const_lv26_281 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010000001";
    constant ap_const_lv26_3FFFCAF : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110010101111";
    constant ap_const_lv26_543 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010101000011";
    constant ap_const_lv26_25C : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001001011100";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv26_26B : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001001101011";
    constant ap_const_lv26_2DB : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001011011011";
    constant ap_const_lv24_4C : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001001100";
    constant ap_const_lv26_304 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001100000100";
    constant ap_const_lv26_3FFFDEE : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110111101110";
    constant ap_const_lv26_3FFFDD4 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110111010100";
    constant ap_const_lv26_3FFFEE3 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111011100011";
    constant ap_const_lv26_3FFFED6 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111011010110";
    constant ap_const_lv26_3FFFED3 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111011010011";
    constant ap_const_lv26_3FFFDC5 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110111000101";
    constant ap_const_lv26_366 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001101100110";
    constant ap_const_lv26_489 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010010001001";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_178 : STD_LOGIC_VECTOR (15 downto 0) := "0000000101111000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_46 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000110";
    constant ap_const_lv16_FFDA : STD_LOGIC_VECTOR (15 downto 0) := "1111111111011010";
    constant ap_const_lv16_FF8C : STD_LOGIC_VECTOR (15 downto 0) := "1111111110001100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_359_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_389 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_fu_369_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_393 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal reg_397 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal sext_ln70_fu_401_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_reg_925 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln818_1_reg_930 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_read19_reg_935 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_fu_452_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_reg_940 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_2_fu_458_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln70_2_reg_945 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln813_15_fu_481_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_15_reg_950 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_23_fu_487_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_23_reg_955 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_3_fu_500_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_3_reg_960 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln818_7_reg_966 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln813_31_fu_545_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln813_31_reg_971 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_read311_reg_976 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal sext_ln70_4_fu_554_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_4_reg_981 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln813_8_fu_560_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_8_reg_986 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_16_fu_566_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_16_reg_991 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_24_fu_580_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_24_reg_996 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal add_ln813_32_fu_586_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_32_reg_1001 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_6_fu_592_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_6_reg_1006 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln818_17_reg_1011 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_read513_reg_1016 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_18_reg_1022 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_7_fu_644_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_7_reg_1027 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln818_20_reg_1033 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal trunc_ln818_21_reg_1038 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read715_reg_1043 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read614_reg_1048 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_2_fu_649_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1270_2_reg_1054 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln813_14_fu_719_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_14_reg_1059 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_3_fu_759_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1270_3_reg_1064 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln813_22_fu_790_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_22_reg_1070 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read5 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read7 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_184_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_5_fu_572_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_184_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_fu_185_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_fu_447_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_185_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_184_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_185_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_379_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln70_fu_401_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_407_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_407_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal shl_ln1273_2_fu_419_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_2_fu_419_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1273_2_fu_427_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln1273_fu_415_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal r_V_5_fu_431_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln1270_fu_447_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_379_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln818_4_fu_467_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln818_4_fu_467_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln818_fu_463_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_1_fu_477_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_3_fu_500_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_3_fu_505_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_3_fu_505_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal shl_ln1273_4_fu_517_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_4_fu_517_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1273_3_fu_513_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln1273_4_fu_525_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal r_V_9_fu_529_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln70_8_fu_493_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln70_9_fu_496_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln70_4_fu_554_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_2_fu_551_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_3_fu_576_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_6_fu_592_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_5_fu_598_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_5_fu_598_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln1273_5_fu_606_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal shl_ln1273_6_fu_616_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_6_fu_616_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sub_ln1273_fu_610_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln1273_6_fu_624_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal r_V_15_fu_628_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln70_7_fu_644_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_2_fu_649_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_1_fu_655_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_10_fu_663_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_10_fu_663_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln1273_9_fu_671_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal shl_ln1273_1_fu_655_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_20_fu_675_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln818_27_fu_681_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_11_fu_701_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_12_fu_707_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_10_fu_695_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_13_fu_713_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_9_fu_691_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_s_fu_732_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln1273_9_fu_725_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1273_8_fu_739_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_19_fu_743_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln813_19_fu_772_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_24_fu_749_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_20_fu_778_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_18_fu_767_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_21_fu_784_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_17_fu_763_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_8_fu_806_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal shl_ln1273_7_fu_799_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1273_7_fu_813_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_18_fu_817_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln818_4_fu_796_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_27_fu_842_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_28_fu_848_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_26_fu_837_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_29_fu_854_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_25_fu_833_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln813_fu_866_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_22_fu_823_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_35_fu_879_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_36_fu_885_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_34_fu_874_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_37_fu_891_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_33_fu_869_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_30_fu_860_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_38_fu_897_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_bincls_axilite_mul_16s_13s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    mul_16s_13s_26_1_1_U258 : component myproject_bincls_axilite_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => grp_fu_184_p0,
        din1 => grp_fu_184_p1,
        dout => grp_fu_184_p2);

    mul_16s_13s_26_1_1_U259 : component myproject_bincls_axilite_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => grp_fu_185_p0,
        din1 => grp_fu_185_p1,
        dout => grp_fu_185_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                add_ln813_14_reg_1059 <= add_ln813_14_fu_719_p2;
                p_read614_reg_1048 <= ap_port_reg_p_read6;
                p_read715_reg_1043 <= ap_port_reg_p_read7;
                sext_ln1270_2_reg_1054 <= sext_ln1270_2_fu_649_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln813_15_reg_950 <= add_ln813_15_fu_481_p2;
                add_ln813_23_reg_955 <= add_ln813_23_fu_487_p2;
                sext_ln70_2_reg_945 <= sext_ln70_2_fu_458_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln813_16_reg_991 <= add_ln813_16_fu_566_p2;
                add_ln813_8_reg_986 <= add_ln813_8_fu_560_p2;
                p_read311_reg_976 <= ap_port_reg_p_read3;
                sext_ln70_4_reg_981 <= sext_ln70_4_fu_554_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                add_ln813_22_reg_1070 <= add_ln813_22_fu_790_p2;
                sext_ln1270_3_reg_1064 <= sext_ln1270_3_fu_759_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln813_24_reg_996 <= add_ln813_24_fu_580_p2;
                add_ln813_32_reg_1001 <= add_ln813_32_fu_586_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln813_31_reg_971 <= add_ln813_31_fu_545_p2;
                sext_ln70_3_reg_960 <= sext_ln70_3_fu_500_p1;
                trunc_ln818_7_reg_966 <= r_V_9_fu_529_p2(22 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln813_reg_940 <= add_ln813_fu_452_p2;
                p_read19_reg_935 <= ap_port_reg_p_read1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                ap_port_reg_p_read1 <= p_read1;
                ap_port_reg_p_read2 <= p_read2;
                ap_port_reg_p_read3 <= p_read3;
                ap_port_reg_p_read4 <= p_read4;
                ap_port_reg_p_read5 <= p_read5;
                ap_port_reg_p_read6 <= p_read6;
                ap_port_reg_p_read7 <= p_read7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                p_read513_reg_1016 <= ap_port_reg_p_read5;
                sext_ln70_7_reg_1027 <= sext_ln70_7_fu_644_p1;
                trunc_ln818_18_reg_1022 <= grp_fu_184_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then
                reg_389 <= grp_fu_184_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state1))) then
                reg_393 <= grp_fu_185_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state5))) then
                reg_397 <= grp_fu_185_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                sext_ln70_6_reg_1006 <= sext_ln70_6_fu_592_p1;
                trunc_ln818_17_reg_1011 <= r_V_15_fu_628_p2(22 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                sext_ln70_reg_925 <= sext_ln70_fu_401_p1;
                trunc_ln818_1_reg_930 <= r_V_5_fu_431_p2(21 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                trunc_ln818_20_reg_1033 <= grp_fu_184_p2(25 downto 10);
                trunc_ln818_21_reg_1038 <= grp_fu_185_p2(25 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    add_ln813_10_fu_695_p2 <= std_logic_vector(unsigned(reg_389) + unsigned(reg_397));
    add_ln813_11_fu_701_p2 <= std_logic_vector(unsigned(trunc_ln818_27_fu_681_p4) + unsigned(ap_const_lv16_178));
    add_ln813_12_fu_707_p2 <= std_logic_vector(unsigned(add_ln813_11_fu_701_p2) + unsigned(grp_fu_359_p4));
    add_ln813_13_fu_713_p2 <= std_logic_vector(unsigned(add_ln813_12_fu_707_p2) + unsigned(add_ln813_10_fu_695_p2));
    add_ln813_14_fu_719_p2 <= std_logic_vector(unsigned(add_ln813_13_fu_713_p2) + unsigned(add_ln813_9_fu_691_p2));
    add_ln813_15_fu_481_p2 <= std_logic_vector(unsigned(reg_393) + unsigned(sext_ln818_fu_463_p1));
    add_ln813_16_fu_566_p2 <= std_logic_vector(signed(sext_ln818_2_fu_551_p1) + signed(grp_fu_369_p4));
    add_ln813_17_fu_763_p2 <= std_logic_vector(unsigned(add_ln813_16_reg_991) + unsigned(add_ln813_15_reg_950));
    add_ln813_18_fu_767_p2 <= std_logic_vector(unsigned(reg_393) + unsigned(trunc_ln818_20_reg_1033));
    add_ln813_19_fu_772_p2 <= std_logic_vector(unsigned(grp_fu_369_p4) + unsigned(ap_const_lv16_46));
    add_ln813_20_fu_778_p2 <= std_logic_vector(unsigned(add_ln813_19_fu_772_p2) + unsigned(trunc_ln818_24_fu_749_p4));
    add_ln813_21_fu_784_p2 <= std_logic_vector(unsigned(add_ln813_20_fu_778_p2) + unsigned(add_ln813_18_fu_767_p2));
    add_ln813_22_fu_790_p2 <= std_logic_vector(unsigned(add_ln813_21_fu_784_p2) + unsigned(add_ln813_17_fu_763_p2));
    add_ln813_23_fu_487_p2 <= std_logic_vector(unsigned(reg_389) + unsigned(sext_ln818_1_fu_477_p1));
    add_ln813_24_fu_580_p2 <= std_logic_vector(unsigned(reg_389) + unsigned(sext_ln818_3_fu_576_p1));
    add_ln813_25_fu_833_p2 <= std_logic_vector(unsigned(add_ln813_24_reg_996) + unsigned(add_ln813_23_reg_955));
    add_ln813_26_fu_837_p2 <= std_logic_vector(signed(sext_ln818_4_fu_796_p1) + signed(trunc_ln818_21_reg_1038));
    add_ln813_27_fu_842_p2 <= std_logic_vector(unsigned(grp_fu_359_p4) + unsigned(ap_const_lv16_FFDA));
    add_ln813_28_fu_848_p2 <= std_logic_vector(unsigned(add_ln813_27_fu_842_p2) + unsigned(reg_397));
    add_ln813_29_fu_854_p2 <= std_logic_vector(unsigned(add_ln813_28_fu_848_p2) + unsigned(add_ln813_26_fu_837_p2));
    add_ln813_30_fu_860_p2 <= std_logic_vector(unsigned(add_ln813_29_fu_854_p2) + unsigned(add_ln813_25_fu_833_p2));
    add_ln813_31_fu_545_p2 <= std_logic_vector(signed(sext_ln70_8_fu_493_p1) + signed(sext_ln70_9_fu_496_p1));
    add_ln813_32_fu_586_p2 <= std_logic_vector(unsigned(reg_397) + unsigned(grp_fu_369_p4));
    add_ln813_33_fu_869_p2 <= std_logic_vector(unsigned(add_ln813_32_reg_1001) + unsigned(sext_ln813_fu_866_p1));
    add_ln813_34_fu_874_p2 <= std_logic_vector(unsigned(trunc_ln818_18_reg_1022) + unsigned(trunc_ln818_22_fu_823_p4));
    add_ln813_35_fu_879_p2 <= std_logic_vector(unsigned(grp_fu_369_p4) + unsigned(ap_const_lv16_FF8C));
    add_ln813_36_fu_885_p2 <= std_logic_vector(unsigned(add_ln813_35_fu_879_p2) + unsigned(reg_389));
    add_ln813_37_fu_891_p2 <= std_logic_vector(unsigned(add_ln813_36_fu_885_p2) + unsigned(add_ln813_34_fu_874_p2));
    add_ln813_38_fu_897_p2 <= std_logic_vector(unsigned(add_ln813_37_fu_891_p2) + unsigned(add_ln813_33_fu_869_p2));
    add_ln813_8_fu_560_p2 <= std_logic_vector(unsigned(reg_393) + unsigned(grp_fu_359_p4));
    add_ln813_9_fu_691_p2 <= std_logic_vector(unsigned(add_ln813_8_reg_986) + unsigned(add_ln813_reg_940));
    add_ln813_fu_452_p2 <= std_logic_vector(unsigned(reg_389) + unsigned(grp_fu_369_p4));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln813_14_reg_1059;
    ap_return_1 <= add_ln813_22_reg_1070;
    ap_return_2 <= add_ln813_30_fu_860_p2;
    ap_return_3 <= add_ln813_38_fu_897_p2;

    grp_fu_184_p0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state12, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state11, sext_ln70_fu_401_p1, sext_ln70_reg_925, sext_ln70_2_fu_458_p1, sext_ln70_2_reg_945, ap_CS_fsm_state3, sext_ln70_3_reg_960, ap_CS_fsm_state6, sext_ln70_4_fu_554_p1, ap_CS_fsm_state7, sext_ln70_6_fu_592_p1, sext_ln70_6_reg_1006, sext_ln70_7_reg_1027, ap_CS_fsm_state10, sext_ln1270_2_fu_649_p1, sext_ln1270_2_reg_1054, sext_ln1270_3_reg_1064, sext_ln70_5_fu_572_p1, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_184_p0 <= sext_ln1270_3_reg_1064(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_184_p0 <= sext_ln1270_2_reg_1054(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_184_p0 <= sext_ln1270_2_fu_649_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_184_p0 <= sext_ln70_7_reg_1027(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_184_p0 <= sext_ln70_6_reg_1006(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_184_p0 <= sext_ln70_6_fu_592_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_184_p0 <= sext_ln70_5_fu_572_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_184_p0 <= sext_ln70_4_fu_554_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_184_p0 <= sext_ln70_3_reg_960(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_184_p0 <= sext_ln70_2_reg_945(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_184_p0 <= sext_ln70_2_fu_458_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_184_p0 <= sext_ln70_reg_925(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_184_p0 <= sext_ln70_fu_401_p1(16 - 1 downto 0);
        else 
            grp_fu_184_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_184_p1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state12, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state10, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_184_p1 <= ap_const_lv26_25C(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_184_p1 <= ap_const_lv26_543(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_184_p1 <= ap_const_lv26_3FFFCAF(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_184_p1 <= ap_const_lv26_281(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_184_p1 <= ap_const_lv26_139(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_184_p1 <= ap_const_lv26_1A3(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_184_p1 <= ap_const_lv24_FFFFAC(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_184_p1 <= ap_const_lv26_2B9(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_184_p1 <= ap_const_lv26_145(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_184_p1 <= ap_const_lv24_5D(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_184_p1 <= ap_const_lv24_FFFF85(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_184_p1 <= ap_const_lv26_135(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_184_p1 <= ap_const_lv26_3AC(13 - 1 downto 0);
        else 
            grp_fu_184_p1 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_185_p0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state12, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state11, sext_ln70_fu_401_p1, sext_ln70_2_fu_458_p1, ap_CS_fsm_state3, sext_ln70_3_fu_500_p1, sext_ln70_3_reg_960, ap_CS_fsm_state6, sext_ln70_4_fu_554_p1, sext_ln70_4_reg_981, ap_CS_fsm_state7, sext_ln70_6_fu_592_p1, sext_ln70_7_fu_644_p1, sext_ln70_7_reg_1027, ap_CS_fsm_state10, sext_ln1270_2_fu_649_p1, sext_ln1270_3_fu_759_p1, sext_ln1270_3_reg_1064, ap_CS_fsm_state13, sext_ln1270_fu_447_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_185_p0 <= sext_ln1270_3_reg_1064(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_185_p0 <= sext_ln1270_3_fu_759_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_fu_185_p0 <= sext_ln1270_2_fu_649_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_185_p0 <= sext_ln70_7_reg_1027(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_185_p0 <= sext_ln70_7_fu_644_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_185_p0 <= sext_ln70_6_fu_592_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_185_p0 <= sext_ln70_4_reg_981(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_185_p0 <= sext_ln70_4_fu_554_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_185_p0 <= sext_ln70_3_reg_960(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_185_p0 <= sext_ln70_3_fu_500_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_185_p0 <= sext_ln70_2_fu_458_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_185_p0 <= sext_ln1270_fu_447_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_185_p0 <= sext_ln70_fu_401_p1(16 - 1 downto 0);
        else 
            grp_fu_185_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_185_p1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state8, ap_CS_fsm_state12, ap_CS_fsm_state4, ap_CS_fsm_state9, ap_CS_fsm_state11, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state10, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            grp_fu_185_p1 <= ap_const_lv26_489(13 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            grp_fu_185_p1 <= ap_const_lv26_366(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_fu_185_p1 <= ap_const_lv26_3FFFDC5(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_fu_185_p1 <= ap_const_lv26_3FFFED3(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_185_p1 <= ap_const_lv26_3FFFED6(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_185_p1 <= ap_const_lv26_3FFFEE3(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_185_p1 <= ap_const_lv26_3FFFDD4(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_185_p1 <= ap_const_lv26_3FFFDEE(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_185_p1 <= ap_const_lv26_304(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_185_p1 <= ap_const_lv24_4C(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_185_p1 <= ap_const_lv26_2DB(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_185_p1 <= ap_const_lv26_26B(13 - 1 downto 0);
        else 
            grp_fu_185_p1 <= "XXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_359_p4 <= grp_fu_184_p2(25 downto 10);
    grp_fu_369_p4 <= grp_fu_185_p2(25 downto 10);
    grp_fu_379_p1 <= grp_fu_184_p2(24 - 1 downto 0);
    grp_fu_379_p4 <= grp_fu_379_p1(23 downto 10);
    r_V_15_fu_628_p2 <= std_logic_vector(unsigned(sub_ln1273_fu_610_p2) - unsigned(sext_ln1273_6_fu_624_p1));
    r_V_18_fu_817_p2 <= std_logic_vector(unsigned(shl_ln1273_7_fu_799_p3) - unsigned(sext_ln1273_7_fu_813_p1));
    r_V_19_fu_743_p2 <= std_logic_vector(unsigned(shl_ln1273_9_fu_725_p3) - unsigned(sext_ln1273_8_fu_739_p1));
    r_V_20_fu_675_p2 <= std_logic_vector(signed(sext_ln1273_9_fu_671_p1) - signed(shl_ln1273_1_fu_655_p3));
    r_V_5_fu_431_p2 <= std_logic_vector(signed(sext_ln1273_2_fu_427_p1) - signed(sext_ln1273_fu_415_p1));
    r_V_9_fu_529_p2 <= std_logic_vector(signed(sext_ln1273_3_fu_513_p1) + signed(sext_ln1273_4_fu_525_p1));
    sext_ln1270_2_fu_649_p0 <= ap_port_reg_p_read6;
        sext_ln1270_2_fu_649_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1270_2_fu_649_p0),26));

        sext_ln1270_3_fu_759_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read715_reg_1043),26));

    sext_ln1270_fu_447_p0 <= ap_port_reg_p_read1;
        sext_ln1270_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1270_fu_447_p0),26));

        sext_ln1273_2_fu_427_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_2_fu_419_p3),22));

        sext_ln1273_3_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_3_fu_505_p3),23));

        sext_ln1273_4_fu_525_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_4_fu_517_p3),23));

        sext_ln1273_5_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_5_fu_598_p3),23));

        sext_ln1273_6_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_6_fu_616_p3),23));

        sext_ln1273_7_fu_813_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_8_fu_806_p3),26));

        sext_ln1273_8_fu_739_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_s_fu_732_p3),26));

        sext_ln1273_9_fu_671_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_10_fu_663_p3),26));

        sext_ln1273_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_407_p3),22));

        sext_ln70_2_fu_458_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read19_reg_935),24));

    sext_ln70_3_fu_500_p0 <= ap_port_reg_p_read2;
        sext_ln70_3_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_3_fu_500_p0),26));

    sext_ln70_4_fu_554_p0 <= ap_port_reg_p_read3;
        sext_ln70_4_fu_554_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_4_fu_554_p0),26));

        sext_ln70_5_fu_572_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read311_reg_976),24));

    sext_ln70_6_fu_592_p0 <= ap_port_reg_p_read4;
        sext_ln70_6_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_6_fu_592_p0),26));

    sext_ln70_7_fu_644_p0 <= ap_port_reg_p_read5;
        sext_ln70_7_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_7_fu_644_p0),26));

        sext_ln70_8_fu_493_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_1_reg_930),15));

        sext_ln70_9_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_379_p4),15));

    sext_ln70_fu_401_p0 <= p_read;
        sext_ln70_fu_401_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_fu_401_p0),26));

        sext_ln813_fu_866_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_31_reg_971),16));

        sext_ln818_1_fu_477_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_4_fu_467_p4),16));

        sext_ln818_2_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_7_reg_966),16));

        sext_ln818_3_fu_576_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_379_p4),16));

        sext_ln818_4_fu_796_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_17_reg_1011),16));

        sext_ln818_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_379_p4),16));

    shl_ln1273_10_fu_663_p1 <= ap_port_reg_p_read7;
    shl_ln1273_10_fu_663_p3 <= (shl_ln1273_10_fu_663_p1 & ap_const_lv5_0);
    shl_ln1273_1_fu_655_p1 <= ap_port_reg_p_read7;
    shl_ln1273_1_fu_655_p3 <= (shl_ln1273_1_fu_655_p1 & ap_const_lv10_0);
    shl_ln1273_2_fu_419_p1 <= p_read;
    shl_ln1273_2_fu_419_p3 <= (shl_ln1273_2_fu_419_p1 & ap_const_lv2_0);
    shl_ln1273_3_fu_505_p1 <= ap_port_reg_p_read2;
    shl_ln1273_3_fu_505_p3 <= (shl_ln1273_3_fu_505_p1 & ap_const_lv6_0);
    shl_ln1273_4_fu_517_p1 <= ap_port_reg_p_read2;
    shl_ln1273_4_fu_517_p3 <= (shl_ln1273_4_fu_517_p1 & ap_const_lv2_0);
    shl_ln1273_5_fu_598_p1 <= ap_port_reg_p_read4;
    shl_ln1273_5_fu_598_p3 <= (shl_ln1273_5_fu_598_p1 & ap_const_lv6_0);
    shl_ln1273_6_fu_616_p1 <= ap_port_reg_p_read4;
    shl_ln1273_6_fu_616_p3 <= (shl_ln1273_6_fu_616_p1 & ap_const_lv3_0);
    shl_ln1273_7_fu_799_p3 <= (p_read513_reg_1016 & ap_const_lv10_0);
    shl_ln1273_8_fu_806_p3 <= (p_read513_reg_1016 & ap_const_lv5_0);
    shl_ln1273_9_fu_725_p3 <= (p_read614_reg_1048 & ap_const_lv10_0);
    shl_ln1273_s_fu_732_p3 <= (p_read614_reg_1048 & ap_const_lv8_0);
    shl_ln_fu_407_p1 <= p_read;
    shl_ln_fu_407_p3 <= (shl_ln_fu_407_p1 & ap_const_lv5_0);
    sub_ln1273_fu_610_p2 <= std_logic_vector(unsigned(ap_const_lv23_0) - unsigned(sext_ln1273_5_fu_606_p1));
    trunc_ln818_22_fu_823_p4 <= r_V_18_fu_817_p2(25 downto 10);
    trunc_ln818_24_fu_749_p4 <= r_V_19_fu_743_p2(25 downto 10);
    trunc_ln818_27_fu_681_p4 <= r_V_20_fu_675_p2(25 downto 10);
    trunc_ln818_4_fu_467_p1 <= grp_fu_185_p2(24 - 1 downto 0);
    trunc_ln818_4_fu_467_p4 <= trunc_ln818_4_fu_467_p1(23 downto 10);
end behav;
