-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv26_3D2 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001111010010";
    constant ap_const_lv26_3FFFD9A : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110011010";
    constant ap_const_lv26_3FFFA71 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111101001110001";
    constant ap_const_lv26_17D : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000101111101";
    constant ap_const_lv26_1B5 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000110110101";
    constant ap_const_lv26_3FFFCA7 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110010100111";
    constant ap_const_lv25_94 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010010100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv16_172 : STD_LOGIC_VECTOR (15 downto 0) := "0000000101110010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv16_FE8D : STD_LOGIC_VECTOR (15 downto 0) := "1111111010001101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal sext_ln1273_fu_139_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1273_reg_265 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_129_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_reg_270 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_2_reg_275 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_read15_reg_280 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln818_3_reg_286 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_fu_149_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_reg_291 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal trunc_ln818_5_reg_296 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_6_reg_301 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal p_read37_reg_306 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal add_ln813_3_fu_174_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_3_reg_311 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_86_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_fu_144_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1270_1_fu_154_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_1_fu_214_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_86_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_fu_86_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1270_fu_144_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_1_fu_154_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_1_fu_163_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_2_fu_169_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_fu_159_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_1_fu_187_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln_fu_180_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1273_1_fu_194_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal r_V_fu_198_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln818_8_fu_218_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln818_8_fu_218_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln818_4_fu_204_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_fu_228_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_5_fu_237_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_6_fu_243_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_4_fu_232_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_7_fu_248_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_bincls_axilite_mul_16s_12s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    mul_16s_12s_26_1_1_U273 : component myproject_bincls_axilite_mul_16s_12s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        din0 => grp_fu_86_p0,
        din1 => grp_fu_86_p1,
        dout => grp_fu_86_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln813_3_reg_311 <= add_ln813_3_fu_174_p2;
                p_read37_reg_306 <= ap_port_reg_p_read3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                ap_port_reg_p_read1 <= p_read1;
                ap_port_reg_p_read2 <= p_read2;
                ap_port_reg_p_read3 <= p_read3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                p_read15_reg_280 <= ap_port_reg_p_read1;
                trunc_ln818_3_reg_286 <= grp_fu_86_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                sext_ln1273_reg_265 <= sext_ln1273_fu_139_p1;
                trunc_ln_reg_270 <= grp_fu_86_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                sext_ln70_reg_291 <= sext_ln70_fu_149_p1;
                trunc_ln818_5_reg_296 <= grp_fu_86_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                trunc_ln818_2_reg_275 <= grp_fu_86_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                trunc_ln818_6_reg_301 <= grp_fu_86_p2(25 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln813_1_fu_163_p2 <= std_logic_vector(unsigned(grp_fu_129_p4) + unsigned(ap_const_lv16_172));
    add_ln813_2_fu_169_p2 <= std_logic_vector(unsigned(add_ln813_1_fu_163_p2) + unsigned(trunc_ln818_5_reg_296));
    add_ln813_3_fu_174_p2 <= std_logic_vector(unsigned(add_ln813_2_fu_169_p2) + unsigned(add_ln813_fu_159_p2));
    add_ln813_4_fu_232_p2 <= std_logic_vector(unsigned(trunc_ln818_2_reg_275) + unsigned(trunc_ln818_4_fu_204_p4));
    add_ln813_5_fu_237_p2 <= std_logic_vector(signed(sext_ln818_fu_228_p1) + signed(ap_const_lv16_FE8D));
    add_ln813_6_fu_243_p2 <= std_logic_vector(unsigned(add_ln813_5_fu_237_p2) + unsigned(trunc_ln818_6_reg_301));
    add_ln813_7_fu_248_p2 <= std_logic_vector(unsigned(add_ln813_6_fu_243_p2) + unsigned(add_ln813_4_fu_232_p2));
    add_ln813_fu_159_p2 <= std_logic_vector(unsigned(trunc_ln_reg_270) + unsigned(trunc_ln818_3_reg_286));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln813_3_reg_311;
    ap_return_1 <= add_ln813_7_fu_248_p2;
    grp_fu_129_p4 <= grp_fu_86_p2(25 downto 10);

    grp_fu_86_p0_assign_proc : process(ap_CS_fsm_state1, sext_ln1273_fu_139_p1, sext_ln1273_reg_265, ap_CS_fsm_state2, ap_CS_fsm_state3, sext_ln70_fu_149_p1, sext_ln70_reg_291, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, sext_ln1270_fu_144_p1, sext_ln1270_1_fu_154_p1, sext_ln70_1_fu_214_p1, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_86_p0 <= sext_ln70_1_fu_214_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_86_p0 <= sext_ln1270_1_fu_154_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_86_p0 <= sext_ln70_reg_291(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_86_p0 <= sext_ln70_fu_149_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_86_p0 <= sext_ln1270_fu_144_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_86_p0 <= sext_ln1273_reg_265(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_86_p0 <= sext_ln1273_fu_139_p1(16 - 1 downto 0);
        else 
            grp_fu_86_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_86_p1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_86_p1 <= ap_const_lv25_94(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_86_p1 <= ap_const_lv26_3FFFCA7(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_86_p1 <= ap_const_lv26_1B5(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_86_p1 <= ap_const_lv26_17D(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_86_p1 <= ap_const_lv26_3FFFA71(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_86_p1 <= ap_const_lv26_3FFFD9A(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_86_p1 <= ap_const_lv26_3D2(12 - 1 downto 0);
        else 
            grp_fu_86_p1 <= "XXXXXXXXXXXX";
        end if; 
    end process;

    r_V_fu_198_p2 <= std_logic_vector(unsigned(shl_ln_fu_180_p3) - unsigned(sext_ln1273_1_fu_194_p1));
    sext_ln1270_1_fu_154_p0 <= ap_port_reg_p_read3;
        sext_ln1270_1_fu_154_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1270_1_fu_154_p0),26));

    sext_ln1270_fu_144_p0 <= ap_port_reg_p_read1;
        sext_ln1270_fu_144_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1270_fu_144_p0),26));

        sext_ln1273_1_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_1_fu_187_p3),26));

        sext_ln1273_fu_139_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read),26));

        sext_ln70_1_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read37_reg_306),25));

        sext_ln70_fu_149_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_port_reg_p_read2),26));

        sext_ln818_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_8_fu_218_p4),16));

    shl_ln1273_1_fu_187_p3 <= (p_read15_reg_280 & ap_const_lv8_0);
    shl_ln_fu_180_p3 <= (p_read15_reg_280 & ap_const_lv10_0);
    trunc_ln818_4_fu_204_p4 <= r_V_fu_198_p2(25 downto 10);
    trunc_ln818_8_fu_218_p1 <= grp_fu_86_p2(25 - 1 downto 0);
    trunc_ln818_8_fu_218_p4 <= trunc_ln818_8_fu_218_p1(24 downto 10);
end behav;
