-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv26_23C : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000111100";
    constant ap_const_lv26_473 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010001110011";
    constant ap_const_lv26_3FFFE5B : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111001011011";
    constant ap_const_lv26_416 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010000010110";
    constant ap_const_lv26_156 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000101010110";
    constant ap_const_lv26_3FFFECF : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111011001111";
    constant ap_const_lv26_3FFFEC8 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111011001000";
    constant ap_const_lv26_3FFFE89 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111010001001";
    constant ap_const_lv24_67 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000001100111";
    constant ap_const_lv26_3FFFDDA : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110111011010";
    constant ap_const_lv26_4FC : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010011111100";
    constant ap_const_lv25_1FFFF38 : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111100111000";
    constant ap_const_lv24_FFFFA9 : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110101001";
    constant ap_const_lv26_275 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001001110101";
    constant ap_const_lv23_3B : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000111011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv26_3FFFE55 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111001010101";
    constant ap_const_lv26_580 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010110000000";
    constant ap_const_lv25_1FFFF7B : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111101111011";
    constant ap_const_lv26_3FFFD62 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110101100010";
    constant ap_const_lv26_284 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010000100";
    constant ap_const_lv26_3DB : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001111011011";
    constant ap_const_lv26_1A1 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000110100001";
    constant ap_const_lv26_24E : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001001001110";
    constant ap_const_lv26_3FFFE3C : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111000111100";
    constant ap_const_lv26_3FFFAFD : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111101011111101";
    constant ap_const_lv26_4A5 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000010010100101";
    constant ap_const_lv24_FFFF87 : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110000111";
    constant ap_const_lv26_3FFFC3C : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110000111100";
    constant ap_const_lv26_348 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001101001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_EB : STD_LOGIC_VECTOR (15 downto 0) := "0000000011101011";
    constant ap_const_lv16_FFF0 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111110000";
    constant ap_const_lv16_C3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000011000011";
    constant ap_const_lv14_E5 : STD_LOGIC_VECTOR (13 downto 0) := "00000011100101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_485_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_535 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_fu_505_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_539 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fu_515_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_543 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_495_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_547 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal p_read19_reg_1026 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_2_fu_602_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_2_reg_1031 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln813_fu_657_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_reg_1036 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_23_fu_663_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_23_reg_1041 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_fu_677_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1270_reg_1046 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln813_15_fu_683_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_15_reg_1052 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_31_fu_689_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_31_reg_1057 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_2_fu_695_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1270_2_reg_1062 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln813_8_fu_763_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_8_reg_1067 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_16_fu_769_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_16_reg_1072 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_24_fu_775_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_24_reg_1077 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read412_reg_1082 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_32_fu_788_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_32_reg_1087 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_18_reg_1092 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal sext_ln70_5_fu_814_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln70_5_reg_1097 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln818_19_reg_1102 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln818_20_reg_1107 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_21_reg_1112 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_525_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln818_22_reg_1117 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal sext_ln70_6_fu_829_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_6_reg_1122 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln818_23_reg_1127 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_24_reg_1132 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_25_reg_1137 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read715_reg_1142 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_14_fu_873_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_14_reg_1147 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_22_fu_905_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_22_reg_1152 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_30_fu_937_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_30_reg_1157 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read5 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read6 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read7 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_188_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_fu_551_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1270_3_fu_781_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1270_4_fu_808_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_8_fu_839_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_188_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_189_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_1_fu_669_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln70_4_fu_794_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln70_7_fu_949_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal grp_fu_189_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_190_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_3_fu_700_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_190_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_191_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_191_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_189_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_191_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_188_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_190_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_525_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln70_fu_551_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_558_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln_fu_558_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal shl_ln1273_1_fu_570_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_1_fu_570_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1273_fu_566_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln1273_1_fu_578_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal r_V_fu_582_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln_fu_588_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln70_2_fu_602_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_2_fu_607_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_2_fu_607_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln1273_2_fu_615_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal shl_ln1273_3_fu_625_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_3_fu_625_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln1273_fu_619_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln1273_3_fu_633_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal r_V_7_fu_637_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln818_4_fu_643_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln818_fu_598_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_2_fu_653_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_1_fu_673_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_2_fu_695_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_3_fu_700_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_12_fu_705_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln818_12_fu_705_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln1273_4_fu_719_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_4_fu_719_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln1273_5_fu_731_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln1273_5_fu_731_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln1273_4_fu_727_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln1273_5_fu_739_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal r_V_11_fu_743_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln818_13_fu_749_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln818_3_fu_715_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_4_fu_759_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln1270_3_fu_781_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_18_fu_798_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln1270_4_fu_808_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_5_fu_814_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_19_fu_819_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln70_8_fu_839_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_6_fu_836_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_11_fu_856_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_12_fu_862_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_10_fu_850_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_13_fu_867_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_9_fu_846_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_19_fu_888_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_20_fu_894_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_18_fu_883_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_21_fu_899_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_17_fu_879_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_27_fu_920_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_28_fu_926_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_26_fu_915_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_29_fu_931_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_25_fu_911_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_30_fu_953_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln818_30_fu_953_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln818_5_fu_943_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln818_7_fu_946_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln813_fu_963_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln813_35_fu_977_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln813_1_fu_983_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_36_fu_987_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_34_fu_971_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_37_fu_993_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_33_fu_967_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_38_fu_999_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_bincls_axilite_mul_16s_13s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    mul_16s_13s_26_1_1_U340 : component myproject_bincls_axilite_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => grp_fu_188_p0,
        din1 => grp_fu_188_p1,
        dout => grp_fu_188_p2);

    mul_16s_13s_26_1_1_U341 : component myproject_bincls_axilite_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => grp_fu_189_p0,
        din1 => grp_fu_189_p1,
        dout => grp_fu_189_p2);

    mul_16s_13s_26_1_1_U342 : component myproject_bincls_axilite_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => grp_fu_190_p0,
        din1 => grp_fu_190_p1,
        dout => grp_fu_190_p2);

    mul_16s_13s_26_1_1_U343 : component myproject_bincls_axilite_mul_16s_13s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 26)
    port map (
        din0 => grp_fu_191_p0,
        din1 => grp_fu_191_p1,
        dout => grp_fu_191_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln813_14_reg_1147 <= add_ln813_14_fu_873_p2;
                add_ln813_22_reg_1152 <= add_ln813_22_fu_905_p2;
                add_ln813_30_reg_1157 <= add_ln813_30_fu_937_p2;
                p_read715_reg_1142 <= ap_port_reg_p_read7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln813_15_reg_1052 <= add_ln813_15_fu_683_p2;
                add_ln813_31_reg_1057 <= add_ln813_31_fu_689_p2;
                sext_ln1270_reg_1046 <= sext_ln1270_fu_677_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln813_16_reg_1072 <= add_ln813_16_fu_769_p2;
                add_ln813_24_reg_1077 <= add_ln813_24_fu_775_p2;
                add_ln813_8_reg_1067 <= add_ln813_8_fu_763_p2;
                sext_ln1270_2_reg_1062 <= sext_ln1270_2_fu_695_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln813_23_reg_1041 <= add_ln813_23_fu_663_p2;
                add_ln813_reg_1036 <= add_ln813_fu_657_p2;
                p_read19_reg_1026 <= p_read1;
                sext_ln70_2_reg_1031 <= sext_ln70_2_fu_602_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln813_32_reg_1087 <= add_ln813_32_fu_788_p2;
                p_read412_reg_1082 <= ap_port_reg_p_read4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                ap_port_reg_p_read2 <= p_read2;
                ap_port_reg_p_read3 <= p_read3;
                ap_port_reg_p_read4 <= p_read4;
                ap_port_reg_p_read5 <= p_read5;
                ap_port_reg_p_read6 <= p_read6;
                ap_port_reg_p_read7 <= p_read7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state1))) then
                reg_535 <= grp_fu_189_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1)))) then
                reg_539 <= grp_fu_188_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2))) then
                reg_543 <= grp_fu_190_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then
                reg_547 <= grp_fu_191_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                sext_ln70_5_reg_1097 <= sext_ln70_5_fu_814_p1;
                trunc_ln818_18_reg_1092 <= trunc_ln818_18_fu_798_p1(24 downto 10);
                trunc_ln818_19_reg_1102 <= trunc_ln818_19_fu_819_p1(23 downto 10);
                trunc_ln818_20_reg_1107 <= grp_fu_188_p2(25 downto 10);
                trunc_ln818_21_reg_1112 <= grp_fu_190_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                sext_ln70_6_reg_1122 <= sext_ln70_6_fu_829_p1;
                trunc_ln818_22_reg_1117 <= grp_fu_525_p1(23 downto 10);
                trunc_ln818_23_reg_1127 <= grp_fu_191_p2(25 downto 10);
                trunc_ln818_24_reg_1132 <= grp_fu_188_p2(25 downto 10);
                trunc_ln818_25_reg_1137 <= grp_fu_190_p2(25 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln813_10_fu_850_p2 <= std_logic_vector(unsigned(reg_547) + unsigned(sext_ln818_6_fu_836_p1));
    add_ln813_11_fu_856_p2 <= std_logic_vector(unsigned(grp_fu_495_p4) + unsigned(ap_const_lv16_EB));
    add_ln813_12_fu_862_p2 <= std_logic_vector(unsigned(add_ln813_11_fu_856_p2) + unsigned(trunc_ln818_23_reg_1127));
    add_ln813_13_fu_867_p2 <= std_logic_vector(unsigned(add_ln813_12_fu_862_p2) + unsigned(add_ln813_10_fu_850_p2));
    add_ln813_14_fu_873_p2 <= std_logic_vector(unsigned(add_ln813_13_fu_867_p2) + unsigned(add_ln813_9_fu_846_p2));
    add_ln813_15_fu_683_p2 <= std_logic_vector(unsigned(reg_535) + unsigned(sext_ln818_1_fu_673_p1));
    add_ln813_16_fu_769_p2 <= std_logic_vector(unsigned(reg_543) + unsigned(sext_ln818_3_fu_715_p1));
    add_ln813_17_fu_879_p2 <= std_logic_vector(unsigned(add_ln813_16_reg_1072) + unsigned(add_ln813_15_reg_1052));
    add_ln813_18_fu_883_p2 <= std_logic_vector(unsigned(reg_539) + unsigned(trunc_ln818_20_reg_1107));
    add_ln813_19_fu_888_p2 <= std_logic_vector(unsigned(grp_fu_505_p4) + unsigned(ap_const_lv16_FFF0));
    add_ln813_20_fu_894_p2 <= std_logic_vector(unsigned(add_ln813_19_fu_888_p2) + unsigned(trunc_ln818_24_reg_1132));
    add_ln813_21_fu_899_p2 <= std_logic_vector(unsigned(add_ln813_20_fu_894_p2) + unsigned(add_ln813_18_fu_883_p2));
    add_ln813_22_fu_905_p2 <= std_logic_vector(unsigned(add_ln813_21_fu_899_p2) + unsigned(add_ln813_17_fu_879_p2));
    add_ln813_23_fu_663_p2 <= std_logic_vector(unsigned(grp_fu_495_p4) + unsigned(sext_ln818_2_fu_653_p1));
    add_ln813_24_fu_775_p2 <= std_logic_vector(unsigned(grp_fu_485_p4) + unsigned(sext_ln818_4_fu_759_p1));
    add_ln813_25_fu_911_p2 <= std_logic_vector(unsigned(add_ln813_24_reg_1077) + unsigned(add_ln813_23_reg_1041));
    add_ln813_26_fu_915_p2 <= std_logic_vector(unsigned(reg_543) + unsigned(trunc_ln818_21_reg_1112));
    add_ln813_27_fu_920_p2 <= std_logic_vector(unsigned(grp_fu_515_p4) + unsigned(ap_const_lv16_C3));
    add_ln813_28_fu_926_p2 <= std_logic_vector(unsigned(add_ln813_27_fu_920_p2) + unsigned(trunc_ln818_25_reg_1137));
    add_ln813_29_fu_931_p2 <= std_logic_vector(unsigned(add_ln813_28_fu_926_p2) + unsigned(add_ln813_26_fu_915_p2));
    add_ln813_30_fu_937_p2 <= std_logic_vector(unsigned(add_ln813_29_fu_931_p2) + unsigned(add_ln813_25_fu_911_p2));
    add_ln813_31_fu_689_p2 <= std_logic_vector(unsigned(reg_539) + unsigned(grp_fu_495_p4));
    add_ln813_32_fu_788_p2 <= std_logic_vector(unsigned(reg_547) + unsigned(grp_fu_485_p4));
    add_ln813_33_fu_967_p2 <= std_logic_vector(unsigned(add_ln813_32_reg_1087) + unsigned(add_ln813_31_reg_1057));
    add_ln813_34_fu_971_p2 <= std_logic_vector(signed(sext_ln818_5_fu_943_p1) + signed(sext_ln818_7_fu_946_p1));
    add_ln813_35_fu_977_p2 <= std_logic_vector(signed(sext_ln813_fu_963_p1) + signed(ap_const_lv14_E5));
    add_ln813_36_fu_987_p2 <= std_logic_vector(signed(sext_ln813_1_fu_983_p1) + signed(reg_535));
    add_ln813_37_fu_993_p2 <= std_logic_vector(unsigned(add_ln813_36_fu_987_p2) + unsigned(add_ln813_34_fu_971_p2));
    add_ln813_38_fu_999_p2 <= std_logic_vector(unsigned(add_ln813_37_fu_993_p2) + unsigned(add_ln813_33_fu_967_p2));
    add_ln813_8_fu_763_p2 <= std_logic_vector(unsigned(reg_539) + unsigned(grp_fu_505_p4));
    add_ln813_9_fu_846_p2 <= std_logic_vector(unsigned(add_ln813_8_reg_1067) + unsigned(add_ln813_reg_1036));
    add_ln813_fu_657_p2 <= std_logic_vector(signed(sext_ln818_fu_598_p1) + signed(grp_fu_515_p4));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln813_14_reg_1147;
    ap_return_1 <= add_ln813_22_reg_1152;
    ap_return_2 <= add_ln813_30_reg_1157;
    ap_return_3 <= add_ln813_38_fu_999_p2;

    grp_fu_188_p0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state7, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state3, sext_ln1270_fu_677_p1, sext_ln1270_2_fu_695_p1, ap_CS_fsm_state5, ap_CS_fsm_state6, sext_ln70_6_fu_829_p1, sext_ln70_fu_551_p1, sext_ln1270_3_fu_781_p1, sext_ln1270_4_fu_808_p1, sext_ln70_8_fu_839_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_188_p0 <= sext_ln70_8_fu_839_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_188_p0 <= sext_ln70_6_fu_829_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_188_p0 <= sext_ln1270_4_fu_808_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_188_p0 <= sext_ln1270_3_fu_781_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_188_p0 <= sext_ln1270_2_fu_695_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_188_p0 <= sext_ln1270_fu_677_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_188_p0 <= sext_ln70_fu_551_p1(16 - 1 downto 0);
        else 
            grp_fu_188_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_188_p1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state7, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_188_p1 <= ap_const_lv26_3FFFEC8(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_188_p1 <= ap_const_lv26_3FFFECF(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_188_p1 <= ap_const_lv26_156(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_188_p1 <= ap_const_lv26_416(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_188_p1 <= ap_const_lv26_3FFFE5B(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_188_p1 <= ap_const_lv26_473(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_188_p1 <= ap_const_lv26_23C(13 - 1 downto 0);
        else 
            grp_fu_188_p1 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_189_p0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state7, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state3, sext_ln1270_reg_1046, sext_ln1270_2_reg_1062, ap_CS_fsm_state5, sext_ln70_5_reg_1097, ap_CS_fsm_state6, sext_ln70_6_reg_1122, sext_ln70_fu_551_p1, sext_ln70_1_fu_669_p1, sext_ln70_4_fu_794_p1, sext_ln70_7_fu_949_p1, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_189_p0 <= sext_ln70_7_fu_949_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_189_p0 <= sext_ln70_6_reg_1122(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_189_p0 <= sext_ln70_5_reg_1097(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_189_p0 <= sext_ln70_4_fu_794_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_189_p0 <= sext_ln1270_2_reg_1062(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_189_p0 <= sext_ln1270_reg_1046(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_189_p0 <= sext_ln70_1_fu_669_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_189_p0 <= sext_ln70_fu_551_p1(16 - 1 downto 0);
        else 
            grp_fu_189_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_189_p1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state7, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_189_p1 <= ap_const_lv23_3B(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_189_p1 <= ap_const_lv26_275(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_189_p1 <= ap_const_lv24_FFFFA9(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_189_p1 <= ap_const_lv25_1FFFF38(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_189_p1 <= ap_const_lv26_4FC(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_189_p1 <= ap_const_lv26_3FFFDDA(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_189_p1 <= ap_const_lv24_67(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_189_p1 <= ap_const_lv26_3FFFE89(13 - 1 downto 0);
        else 
            grp_fu_189_p1 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_190_p0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state7, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state3, sext_ln70_2_fu_602_p1, sext_ln1270_fu_677_p1, ap_CS_fsm_state5, ap_CS_fsm_state6, sext_ln70_6_fu_829_p1, sext_ln1270_3_fu_781_p1, sext_ln1270_4_fu_808_p1, sext_ln70_8_fu_839_p1, sext_ln70_3_fu_700_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_190_p0 <= sext_ln70_8_fu_839_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_190_p0 <= sext_ln70_6_fu_829_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_190_p0 <= sext_ln1270_4_fu_808_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_190_p0 <= sext_ln1270_3_fu_781_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_190_p0 <= sext_ln70_3_fu_700_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_190_p0 <= sext_ln1270_fu_677_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_190_p0 <= sext_ln70_2_fu_602_p1(16 - 1 downto 0);
        else 
            grp_fu_190_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_190_p1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state7, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_190_p1 <= ap_const_lv26_1A1(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_190_p1 <= ap_const_lv26_3DB(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_190_p1 <= ap_const_lv26_284(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_190_p1 <= ap_const_lv26_3FFFD62(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_190_p1 <= ap_const_lv25_1FFFF7B(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_190_p1 <= ap_const_lv26_580(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_190_p1 <= ap_const_lv26_3FFFE55(13 - 1 downto 0);
        else 
            grp_fu_190_p1 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_191_p0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state7, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state3, sext_ln70_2_reg_1031, sext_ln1270_reg_1046, ap_CS_fsm_state5, sext_ln70_5_fu_814_p1, ap_CS_fsm_state6, sext_ln70_6_fu_829_p1, sext_ln70_fu_551_p1, sext_ln1270_3_fu_781_p1, sext_ln70_8_fu_839_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_191_p0 <= sext_ln70_8_fu_839_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_191_p0 <= sext_ln70_6_fu_829_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_191_p0 <= sext_ln70_5_fu_814_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_191_p0 <= sext_ln1270_3_fu_781_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_191_p0 <= sext_ln1270_reg_1046(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_191_p0 <= sext_ln70_2_reg_1031(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_191_p0 <= sext_ln70_fu_551_p1(16 - 1 downto 0);
        else 
            grp_fu_191_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_191_p1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state7, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_191_p1 <= ap_const_lv26_348(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_191_p1 <= ap_const_lv26_3FFFC3C(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_191_p1 <= ap_const_lv24_FFFF87(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_191_p1 <= ap_const_lv26_4A5(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_191_p1 <= ap_const_lv26_3FFFAFD(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_191_p1 <= ap_const_lv26_3FFFE3C(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_191_p1 <= ap_const_lv26_24E(13 - 1 downto 0);
        else 
            grp_fu_191_p1 <= "XXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_485_p4 <= grp_fu_189_p2(25 downto 10);
    grp_fu_495_p4 <= grp_fu_191_p2(25 downto 10);
    grp_fu_505_p4 <= grp_fu_188_p2(25 downto 10);
    grp_fu_515_p4 <= grp_fu_190_p2(25 downto 10);
    grp_fu_525_p1 <= grp_fu_189_p2(24 - 1 downto 0);
    grp_fu_525_p4 <= grp_fu_525_p1(23 downto 10);
    r_V_11_fu_743_p2 <= std_logic_vector(signed(sext_ln1273_4_fu_727_p1) + signed(sext_ln1273_5_fu_739_p1));
    r_V_7_fu_637_p2 <= std_logic_vector(unsigned(sub_ln1273_fu_619_p2) - unsigned(sext_ln1273_3_fu_633_p1));
    r_V_fu_582_p2 <= std_logic_vector(signed(sext_ln1273_fu_566_p1) - signed(sext_ln1273_1_fu_578_p1));
    sext_ln1270_2_fu_695_p0 <= ap_port_reg_p_read3;
        sext_ln1270_2_fu_695_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1270_2_fu_695_p0),26));

    sext_ln1270_3_fu_781_p0 <= ap_port_reg_p_read4;
        sext_ln1270_3_fu_781_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1270_3_fu_781_p0),26));

    sext_ln1270_4_fu_808_p0 <= ap_port_reg_p_read5;
        sext_ln1270_4_fu_808_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln1270_4_fu_808_p0),26));

        sext_ln1270_fu_677_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_port_reg_p_read2),26));

        sext_ln1273_1_fu_578_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_1_fu_570_p3),23));

        sext_ln1273_2_fu_615_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_2_fu_607_p3),25));

        sext_ln1273_3_fu_633_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_3_fu_625_p3),25));

        sext_ln1273_4_fu_727_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_4_fu_719_p3),25));

        sext_ln1273_5_fu_739_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1273_5_fu_731_p3),25));

        sext_ln1273_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_558_p3),23));

        sext_ln70_1_fu_669_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read19_reg_1026),24));

    sext_ln70_2_fu_602_p0 <= p_read1;
        sext_ln70_2_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_2_fu_602_p0),26));

    sext_ln70_3_fu_700_p0 <= ap_port_reg_p_read3;
        sext_ln70_3_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_3_fu_700_p0),25));

        sext_ln70_4_fu_794_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read412_reg_1082),25));

    sext_ln70_5_fu_814_p0 <= ap_port_reg_p_read5;
        sext_ln70_5_fu_814_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_5_fu_814_p0),24));

        sext_ln70_6_fu_829_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_port_reg_p_read6),26));

        sext_ln70_7_fu_949_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read715_reg_1142),23));

    sext_ln70_8_fu_839_p0 <= ap_port_reg_p_read7;
        sext_ln70_8_fu_839_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_8_fu_839_p0),26));

    sext_ln70_fu_551_p0 <= p_read;
        sext_ln70_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln70_fu_551_p0),26));

        sext_ln813_1_fu_983_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln813_35_fu_977_p2),16));

        sext_ln813_fu_963_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_30_fu_953_p4),14));

        sext_ln818_1_fu_673_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_525_p4),16));

        sext_ln818_2_fu_653_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_4_fu_643_p4),16));

        sext_ln818_3_fu_715_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_12_fu_705_p4),16));

        sext_ln818_4_fu_759_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_13_fu_749_p4),16));

        sext_ln818_5_fu_943_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_18_reg_1092),16));

        sext_ln818_6_fu_836_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_19_reg_1102),16));

        sext_ln818_7_fu_946_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln818_22_reg_1117),16));

        sext_ln818_fu_598_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_588_p4),16));

    shl_ln1273_1_fu_570_p1 <= p_read;
    shl_ln1273_1_fu_570_p3 <= (shl_ln1273_1_fu_570_p1 & ap_const_lv2_0);
    shl_ln1273_2_fu_607_p1 <= p_read1;
    shl_ln1273_2_fu_607_p3 <= (shl_ln1273_2_fu_607_p1 & ap_const_lv8_0);
    shl_ln1273_3_fu_625_p1 <= p_read1;
    shl_ln1273_3_fu_625_p3 <= (shl_ln1273_3_fu_625_p1 & ap_const_lv1_0);
    shl_ln1273_4_fu_719_p1 <= ap_port_reg_p_read3;
    shl_ln1273_4_fu_719_p3 <= (shl_ln1273_4_fu_719_p1 & ap_const_lv8_0);
    shl_ln1273_5_fu_731_p1 <= ap_port_reg_p_read3;
    shl_ln1273_5_fu_731_p3 <= (shl_ln1273_5_fu_731_p1 & ap_const_lv4_0);
    shl_ln_fu_558_p1 <= p_read;
    shl_ln_fu_558_p3 <= (shl_ln_fu_558_p1 & ap_const_lv6_0);
    sub_ln1273_fu_619_p2 <= std_logic_vector(unsigned(ap_const_lv25_0) - unsigned(sext_ln1273_2_fu_615_p1));
    trunc_ln818_12_fu_705_p1 <= grp_fu_190_p2(25 - 1 downto 0);
    trunc_ln818_12_fu_705_p4 <= trunc_ln818_12_fu_705_p1(24 downto 10);
    trunc_ln818_13_fu_749_p4 <= r_V_11_fu_743_p2(24 downto 10);
    trunc_ln818_18_fu_798_p1 <= grp_fu_189_p2(25 - 1 downto 0);
    trunc_ln818_19_fu_819_p1 <= grp_fu_191_p2(24 - 1 downto 0);
    trunc_ln818_30_fu_953_p1 <= grp_fu_189_p2(23 - 1 downto 0);
    trunc_ln818_30_fu_953_p4 <= trunc_ln818_30_fu_953_p1(22 downto 10);
    trunc_ln818_4_fu_643_p4 <= r_V_7_fu_637_p2(24 downto 10);
    trunc_ln_fu_588_p4 <= r_V_fu_582_p2(22 downto 10);
end behav;
