-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv26_3FFFBB5 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111101110110101";
    constant ap_const_lv26_2AF : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001010101111";
    constant ap_const_lv26_3FFFE1B : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111000011011";
    constant ap_const_lv26_22B : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000101011";
    constant ap_const_lv26_3B7 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001110110111";
    constant ap_const_lv26_3FFFD85 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110000101";
    constant ap_const_lv26_1FA : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000111111010";
    constant ap_const_lv26_3FFFE9A : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111010011010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv16_CE : STD_LOGIC_VECTOR (15 downto 0) := "0000000011001110";
    constant ap_const_lv16_FF31 : STD_LOGIC_VECTOR (15 downto 0) := "1111111100110001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal sext_ln1270_fu_134_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1270_reg_207 : STD_LOGIC_VECTOR (25 downto 0);
    signal grp_fu_124_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_reg_212 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_2_reg_217 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sext_ln1270_1_fu_139_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1270_1_reg_222 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal trunc_ln818_3_reg_227 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_4_reg_232 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sext_ln1273_fu_144_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln1273_reg_237 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal trunc_ln818_5_reg_242 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln818_6_reg_247 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal sext_ln70_fu_149_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sext_ln70_reg_252 : STD_LOGIC_VECTOR (25 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal add_ln813_3_fu_169_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_3_reg_257 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_p_read3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_76_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_76_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_76_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal add_ln813_1_fu_158_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_2_fu_164_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_fu_154_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_5_fu_179_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_6_fu_185_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_4_fu_175_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln813_7_fu_190_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_bincls_axilite_mul_16s_12s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    mul_16s_12s_26_1_1_U357 : component myproject_bincls_axilite_mul_16s_12s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 12,
        dout_WIDTH => 26)
    port map (
        din0 => grp_fu_76_p0,
        din1 => grp_fu_76_p1,
        dout => grp_fu_76_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln813_3_reg_257 <= add_ln813_3_fu_169_p2;
                sext_ln70_reg_252 <= sext_ln70_fu_149_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                ap_port_reg_p_read1 <= p_read1;
                ap_port_reg_p_read2 <= p_read2;
                ap_port_reg_p_read3 <= p_read3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                sext_ln1270_1_reg_222 <= sext_ln1270_1_fu_139_p1;
                trunc_ln818_3_reg_227 <= grp_fu_76_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                sext_ln1270_reg_207 <= sext_ln1270_fu_134_p1;
                trunc_ln_reg_212 <= grp_fu_76_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                sext_ln1273_reg_237 <= sext_ln1273_fu_144_p1;
                trunc_ln818_5_reg_242 <= grp_fu_76_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                trunc_ln818_2_reg_217 <= grp_fu_76_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                trunc_ln818_4_reg_232 <= grp_fu_76_p2(25 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                trunc_ln818_6_reg_247 <= grp_fu_76_p2(25 downto 10);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln813_1_fu_158_p2 <= std_logic_vector(unsigned(grp_fu_124_p4) + unsigned(ap_const_lv16_CE));
    add_ln813_2_fu_164_p2 <= std_logic_vector(unsigned(add_ln813_1_fu_158_p2) + unsigned(trunc_ln818_5_reg_242));
    add_ln813_3_fu_169_p2 <= std_logic_vector(unsigned(add_ln813_2_fu_164_p2) + unsigned(add_ln813_fu_154_p2));
    add_ln813_4_fu_175_p2 <= std_logic_vector(unsigned(trunc_ln818_2_reg_217) + unsigned(trunc_ln818_4_reg_232));
    add_ln813_5_fu_179_p2 <= std_logic_vector(unsigned(grp_fu_124_p4) + unsigned(ap_const_lv16_FF31));
    add_ln813_6_fu_185_p2 <= std_logic_vector(unsigned(add_ln813_5_fu_179_p2) + unsigned(trunc_ln818_6_reg_247));
    add_ln813_7_fu_190_p2 <= std_logic_vector(unsigned(add_ln813_6_fu_185_p2) + unsigned(add_ln813_4_fu_175_p2));
    add_ln813_fu_154_p2 <= std_logic_vector(unsigned(trunc_ln_reg_212) + unsigned(trunc_ln818_3_reg_227));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= add_ln813_3_reg_257;
    ap_return_1 <= add_ln813_7_fu_190_p2;
    grp_fu_124_p4 <= grp_fu_76_p2(25 downto 10);

    grp_fu_76_p0_assign_proc : process(ap_CS_fsm_state1, sext_ln1270_fu_134_p1, sext_ln1270_reg_207, ap_CS_fsm_state2, sext_ln1270_1_fu_139_p1, sext_ln1270_1_reg_222, ap_CS_fsm_state3, ap_CS_fsm_state4, sext_ln1273_fu_144_p1, sext_ln1273_reg_237, ap_CS_fsm_state5, ap_CS_fsm_state6, sext_ln70_fu_149_p1, sext_ln70_reg_252, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_76_p0 <= sext_ln70_reg_252(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_76_p0 <= sext_ln70_fu_149_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_76_p0 <= sext_ln1273_reg_237(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_76_p0 <= sext_ln1273_fu_144_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_76_p0 <= sext_ln1270_1_reg_222(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_76_p0 <= sext_ln1270_1_fu_139_p1(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_76_p0 <= sext_ln1270_reg_207(16 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_76_p0 <= sext_ln1270_fu_134_p1(16 - 1 downto 0);
        else 
            grp_fu_76_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_76_p1_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            grp_fu_76_p1 <= ap_const_lv26_3FFFE9A(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_76_p1 <= ap_const_lv26_1FA(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            grp_fu_76_p1 <= ap_const_lv26_3FFFD85(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            grp_fu_76_p1 <= ap_const_lv26_3B7(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_76_p1 <= ap_const_lv26_22B(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            grp_fu_76_p1 <= ap_const_lv26_3FFFE1B(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_fu_76_p1 <= ap_const_lv26_2AF(12 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_76_p1 <= ap_const_lv26_3FFFBB5(12 - 1 downto 0);
        else 
            grp_fu_76_p1 <= "XXXXXXXXXXXX";
        end if; 
    end process;

        sext_ln1270_1_fu_139_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_port_reg_p_read1),26));

        sext_ln1270_fu_134_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_read),26));

        sext_ln1273_fu_144_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_port_reg_p_read2),26));

        sext_ln70_fu_149_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ap_port_reg_p_read3),26));

end behav;
