// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] grp_fu_485_p4;
reg   [15:0] reg_535;
wire    ap_CS_fsm_state7;
wire   [15:0] grp_fu_505_p4;
reg   [15:0] reg_539;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state4;
wire   [15:0] grp_fu_515_p4;
reg   [15:0] reg_543;
wire   [15:0] grp_fu_495_p4;
reg   [15:0] reg_547;
wire    ap_CS_fsm_state3;
reg  signed [15:0] p_read19_reg_1026;
wire  signed [25:0] sext_ln70_2_fu_602_p1;
reg  signed [25:0] sext_ln70_2_reg_1031;
wire   [15:0] add_ln813_fu_657_p2;
reg   [15:0] add_ln813_reg_1036;
wire   [15:0] add_ln813_23_fu_663_p2;
reg   [15:0] add_ln813_23_reg_1041;
wire  signed [25:0] sext_ln1270_fu_677_p1;
reg  signed [25:0] sext_ln1270_reg_1046;
wire   [15:0] add_ln813_15_fu_683_p2;
reg   [15:0] add_ln813_15_reg_1052;
wire   [15:0] add_ln813_31_fu_689_p2;
reg   [15:0] add_ln813_31_reg_1057;
wire  signed [25:0] sext_ln1270_2_fu_695_p1;
reg  signed [25:0] sext_ln1270_2_reg_1062;
wire   [15:0] add_ln813_8_fu_763_p2;
reg   [15:0] add_ln813_8_reg_1067;
wire   [15:0] add_ln813_16_fu_769_p2;
reg   [15:0] add_ln813_16_reg_1072;
wire   [15:0] add_ln813_24_fu_775_p2;
reg   [15:0] add_ln813_24_reg_1077;
reg  signed [15:0] p_read412_reg_1082;
wire   [15:0] add_ln813_32_fu_788_p2;
reg   [15:0] add_ln813_32_reg_1087;
reg   [14:0] trunc_ln818_18_reg_1092;
wire    ap_CS_fsm_state5;
wire  signed [23:0] sext_ln70_5_fu_814_p1;
reg  signed [23:0] sext_ln70_5_reg_1097;
reg   [13:0] trunc_ln818_19_reg_1102;
reg   [15:0] trunc_ln818_20_reg_1107;
reg   [15:0] trunc_ln818_21_reg_1112;
wire   [13:0] grp_fu_525_p4;
reg   [13:0] trunc_ln818_22_reg_1117;
wire    ap_CS_fsm_state6;
wire  signed [25:0] sext_ln70_6_fu_829_p1;
reg  signed [25:0] sext_ln70_6_reg_1122;
reg   [15:0] trunc_ln818_23_reg_1127;
reg   [15:0] trunc_ln818_24_reg_1132;
reg   [15:0] trunc_ln818_25_reg_1137;
reg  signed [15:0] p_read715_reg_1142;
wire   [15:0] add_ln813_14_fu_873_p2;
reg   [15:0] add_ln813_14_reg_1147;
wire   [15:0] add_ln813_22_fu_905_p2;
reg   [15:0] add_ln813_22_reg_1152;
wire   [15:0] add_ln813_30_fu_937_p2;
reg   [15:0] add_ln813_30_reg_1157;
reg   [15:0] ap_port_reg_p_read2;
reg   [15:0] ap_port_reg_p_read3;
reg   [15:0] ap_port_reg_p_read4;
reg   [15:0] ap_port_reg_p_read5;
reg   [15:0] ap_port_reg_p_read6;
reg   [15:0] ap_port_reg_p_read7;
reg  signed [15:0] grp_fu_188_p0;
wire  signed [25:0] sext_ln70_fu_551_p1;
wire  signed [25:0] sext_ln1270_3_fu_781_p1;
wire  signed [25:0] sext_ln1270_4_fu_808_p1;
wire  signed [25:0] sext_ln70_8_fu_839_p1;
reg  signed [12:0] grp_fu_188_p1;
reg  signed [15:0] grp_fu_189_p0;
wire  signed [23:0] sext_ln70_1_fu_669_p1;
wire  signed [24:0] sext_ln70_4_fu_794_p1;
wire  signed [22:0] sext_ln70_7_fu_949_p1;
reg  signed [12:0] grp_fu_189_p1;
wire    ap_CS_fsm_state8;
reg  signed [15:0] grp_fu_190_p0;
wire  signed [24:0] sext_ln70_3_fu_700_p1;
reg  signed [12:0] grp_fu_190_p1;
reg  signed [15:0] grp_fu_191_p0;
reg  signed [12:0] grp_fu_191_p1;
wire   [25:0] grp_fu_189_p2;
wire   [25:0] grp_fu_191_p2;
wire   [25:0] grp_fu_188_p2;
wire   [25:0] grp_fu_190_p2;
wire   [23:0] grp_fu_525_p1;
wire  signed [15:0] sext_ln70_fu_551_p0;
wire  signed [15:0] shl_ln_fu_558_p1;
wire   [21:0] shl_ln_fu_558_p3;
wire  signed [15:0] shl_ln1273_1_fu_570_p1;
wire   [17:0] shl_ln1273_1_fu_570_p3;
wire  signed [22:0] sext_ln1273_fu_566_p1;
wire  signed [22:0] sext_ln1273_1_fu_578_p1;
wire   [22:0] r_V_fu_582_p2;
wire   [12:0] trunc_ln_fu_588_p4;
wire  signed [15:0] sext_ln70_2_fu_602_p0;
wire  signed [15:0] shl_ln1273_2_fu_607_p1;
wire   [23:0] shl_ln1273_2_fu_607_p3;
wire  signed [24:0] sext_ln1273_2_fu_615_p1;
wire  signed [15:0] shl_ln1273_3_fu_625_p1;
wire   [16:0] shl_ln1273_3_fu_625_p3;
wire   [24:0] sub_ln1273_fu_619_p2;
wire  signed [24:0] sext_ln1273_3_fu_633_p1;
wire   [24:0] r_V_7_fu_637_p2;
wire   [14:0] trunc_ln818_4_fu_643_p4;
wire  signed [15:0] sext_ln818_fu_598_p1;
wire  signed [15:0] sext_ln818_2_fu_653_p1;
wire  signed [15:0] sext_ln818_1_fu_673_p1;
wire  signed [15:0] sext_ln1270_2_fu_695_p0;
wire  signed [15:0] sext_ln70_3_fu_700_p0;
wire   [24:0] trunc_ln818_12_fu_705_p1;
wire   [14:0] trunc_ln818_12_fu_705_p4;
wire  signed [15:0] shl_ln1273_4_fu_719_p1;
wire   [23:0] shl_ln1273_4_fu_719_p3;
wire  signed [15:0] shl_ln1273_5_fu_731_p1;
wire   [19:0] shl_ln1273_5_fu_731_p3;
wire  signed [24:0] sext_ln1273_4_fu_727_p1;
wire  signed [24:0] sext_ln1273_5_fu_739_p1;
wire   [24:0] r_V_11_fu_743_p2;
wire   [14:0] trunc_ln818_13_fu_749_p4;
wire  signed [15:0] sext_ln818_3_fu_715_p1;
wire  signed [15:0] sext_ln818_4_fu_759_p1;
wire  signed [15:0] sext_ln1270_3_fu_781_p0;
wire   [24:0] trunc_ln818_18_fu_798_p1;
wire  signed [15:0] sext_ln1270_4_fu_808_p0;
wire  signed [15:0] sext_ln70_5_fu_814_p0;
wire   [23:0] trunc_ln818_19_fu_819_p1;
wire  signed [15:0] sext_ln70_8_fu_839_p0;
wire  signed [15:0] sext_ln818_6_fu_836_p1;
wire   [15:0] add_ln813_11_fu_856_p2;
wire   [15:0] add_ln813_12_fu_862_p2;
wire   [15:0] add_ln813_10_fu_850_p2;
wire   [15:0] add_ln813_13_fu_867_p2;
wire   [15:0] add_ln813_9_fu_846_p2;
wire   [15:0] add_ln813_19_fu_888_p2;
wire   [15:0] add_ln813_20_fu_894_p2;
wire   [15:0] add_ln813_18_fu_883_p2;
wire   [15:0] add_ln813_21_fu_899_p2;
wire   [15:0] add_ln813_17_fu_879_p2;
wire   [15:0] add_ln813_27_fu_920_p2;
wire   [15:0] add_ln813_28_fu_926_p2;
wire   [15:0] add_ln813_26_fu_915_p2;
wire   [15:0] add_ln813_29_fu_931_p2;
wire   [15:0] add_ln813_25_fu_911_p2;
wire   [22:0] trunc_ln818_30_fu_953_p1;
wire   [12:0] trunc_ln818_30_fu_953_p4;
wire  signed [15:0] sext_ln818_5_fu_943_p1;
wire  signed [15:0] sext_ln818_7_fu_946_p1;
wire  signed [13:0] sext_ln813_fu_963_p1;
wire   [13:0] add_ln813_35_fu_977_p2;
wire  signed [15:0] sext_ln813_1_fu_983_p1;
wire   [15:0] add_ln813_36_fu_987_p2;
wire   [15:0] add_ln813_34_fu_971_p2;
wire   [15:0] add_ln813_37_fu_993_p2;
wire   [15:0] add_ln813_33_fu_967_p2;
wire   [15:0] add_ln813_38_fu_999_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

myproject_bincls_axilite_mul_16s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_1_1_U340(
    .din0(grp_fu_188_p0),
    .din1(grp_fu_188_p1),
    .dout(grp_fu_188_p2)
);

myproject_bincls_axilite_mul_16s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_1_1_U341(
    .din0(grp_fu_189_p0),
    .din1(grp_fu_189_p1),
    .dout(grp_fu_189_p2)
);

myproject_bincls_axilite_mul_16s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_1_1_U342(
    .din0(grp_fu_190_p0),
    .din1(grp_fu_190_p1),
    .dout(grp_fu_190_p2)
);

myproject_bincls_axilite_mul_16s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_1_1_U343(
    .din0(grp_fu_191_p0),
    .din1(grp_fu_191_p1),
    .dout(grp_fu_191_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln813_14_reg_1147 <= add_ln813_14_fu_873_p2;
        add_ln813_22_reg_1152 <= add_ln813_22_fu_905_p2;
        add_ln813_30_reg_1157 <= add_ln813_30_fu_937_p2;
        p_read715_reg_1142 <= ap_port_reg_p_read7;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln813_15_reg_1052 <= add_ln813_15_fu_683_p2;
        add_ln813_31_reg_1057 <= add_ln813_31_fu_689_p2;
        sext_ln1270_reg_1046 <= sext_ln1270_fu_677_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln813_16_reg_1072 <= add_ln813_16_fu_769_p2;
        add_ln813_24_reg_1077 <= add_ln813_24_fu_775_p2;
        add_ln813_8_reg_1067 <= add_ln813_8_fu_763_p2;
        sext_ln1270_2_reg_1062 <= sext_ln1270_2_fu_695_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln813_23_reg_1041 <= add_ln813_23_fu_663_p2;
        add_ln813_reg_1036 <= add_ln813_fu_657_p2;
        p_read19_reg_1026 <= p_read1;
        sext_ln70_2_reg_1031 <= sext_ln70_2_fu_602_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln813_32_reg_1087 <= add_ln813_32_fu_788_p2;
        p_read412_reg_1082 <= ap_port_reg_p_read4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ap_port_reg_p_read2 <= p_read2;
        ap_port_reg_p_read3 <= p_read3;
        ap_port_reg_p_read4 <= p_read4;
        ap_port_reg_p_read5 <= p_read5;
        ap_port_reg_p_read6 <= p_read6;
        ap_port_reg_p_read7 <= p_read7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state1))) begin
        reg_535 <= {{grp_fu_189_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        reg_539 <= {{grp_fu_188_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        reg_543 <= {{grp_fu_190_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state4))) begin
        reg_547 <= {{grp_fu_191_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        sext_ln70_5_reg_1097 <= sext_ln70_5_fu_814_p1;
        trunc_ln818_18_reg_1092 <= {{trunc_ln818_18_fu_798_p1[24:10]}};
        trunc_ln818_19_reg_1102 <= {{trunc_ln818_19_fu_819_p1[23:10]}};
        trunc_ln818_20_reg_1107 <= {{grp_fu_188_p2[25:10]}};
        trunc_ln818_21_reg_1112 <= {{grp_fu_190_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sext_ln70_6_reg_1122 <= sext_ln70_6_fu_829_p1;
        trunc_ln818_22_reg_1117 <= {{grp_fu_525_p1[23:10]}};
        trunc_ln818_23_reg_1127 <= {{grp_fu_191_p2[25:10]}};
        trunc_ln818_24_reg_1132 <= {{grp_fu_188_p2[25:10]}};
        trunc_ln818_25_reg_1137 <= {{grp_fu_190_p2[25:10]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_188_p0 = sext_ln70_8_fu_839_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_188_p0 = sext_ln70_6_fu_829_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_188_p0 = sext_ln1270_4_fu_808_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_188_p0 = sext_ln1270_3_fu_781_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_188_p0 = sext_ln1270_2_fu_695_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_188_p0 = sext_ln1270_fu_677_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_188_p0 = sext_ln70_fu_551_p1;
    end else begin
        grp_fu_188_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_188_p1 = 26'd67108552;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_188_p1 = 26'd67108559;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_188_p1 = 26'd342;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_188_p1 = 26'd1046;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_188_p1 = 26'd67108443;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_188_p1 = 26'd1139;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_188_p1 = 26'd572;
    end else begin
        grp_fu_188_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_189_p0 = sext_ln70_7_fu_949_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_189_p0 = sext_ln70_6_reg_1122;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_189_p0 = sext_ln70_5_reg_1097;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_189_p0 = sext_ln70_4_fu_794_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_189_p0 = sext_ln1270_2_reg_1062;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_189_p0 = sext_ln1270_reg_1046;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_189_p0 = sext_ln70_1_fu_669_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_189_p0 = sext_ln70_fu_551_p1;
    end else begin
        grp_fu_189_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_189_p1 = 23'd59;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_189_p1 = 26'd629;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_189_p1 = 24'd16777129;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_189_p1 = 25'd33554232;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_189_p1 = 26'd1276;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_189_p1 = 26'd67108314;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_189_p1 = 24'd103;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_189_p1 = 26'd67108489;
    end else begin
        grp_fu_189_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_190_p0 = sext_ln70_8_fu_839_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_190_p0 = sext_ln70_6_fu_829_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_190_p0 = sext_ln1270_4_fu_808_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_190_p0 = sext_ln1270_3_fu_781_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_190_p0 = sext_ln70_3_fu_700_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_190_p0 = sext_ln1270_fu_677_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_190_p0 = sext_ln70_2_fu_602_p1;
    end else begin
        grp_fu_190_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_190_p1 = 26'd417;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_190_p1 = 26'd987;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_190_p1 = 26'd644;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_190_p1 = 26'd67108194;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_190_p1 = 25'd33554299;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_190_p1 = 26'd1408;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_190_p1 = 26'd67108437;
    end else begin
        grp_fu_190_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_191_p0 = sext_ln70_8_fu_839_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_191_p0 = sext_ln70_6_fu_829_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_191_p0 = sext_ln70_5_fu_814_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_191_p0 = sext_ln1270_3_fu_781_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_191_p0 = sext_ln1270_reg_1046;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_191_p0 = sext_ln70_2_reg_1031;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_191_p0 = sext_ln70_fu_551_p1;
    end else begin
        grp_fu_191_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_191_p1 = 26'd840;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_191_p1 = 26'd67107900;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_191_p1 = 24'd16777095;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_191_p1 = 26'd1189;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_191_p1 = 26'd67107581;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_191_p1 = 26'd67108412;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_191_p1 = 26'd590;
    end else begin
        grp_fu_191_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln813_10_fu_850_p2 = ($signed(reg_547) + $signed(sext_ln818_6_fu_836_p1));

assign add_ln813_11_fu_856_p2 = (grp_fu_495_p4 + 16'd235);

assign add_ln813_12_fu_862_p2 = (add_ln813_11_fu_856_p2 + trunc_ln818_23_reg_1127);

assign add_ln813_13_fu_867_p2 = (add_ln813_12_fu_862_p2 + add_ln813_10_fu_850_p2);

assign add_ln813_14_fu_873_p2 = (add_ln813_13_fu_867_p2 + add_ln813_9_fu_846_p2);

assign add_ln813_15_fu_683_p2 = ($signed(reg_535) + $signed(sext_ln818_1_fu_673_p1));

assign add_ln813_16_fu_769_p2 = ($signed(reg_543) + $signed(sext_ln818_3_fu_715_p1));

assign add_ln813_17_fu_879_p2 = (add_ln813_16_reg_1072 + add_ln813_15_reg_1052);

assign add_ln813_18_fu_883_p2 = (reg_539 + trunc_ln818_20_reg_1107);

assign add_ln813_19_fu_888_p2 = ($signed(grp_fu_505_p4) + $signed(16'd65520));

assign add_ln813_20_fu_894_p2 = (add_ln813_19_fu_888_p2 + trunc_ln818_24_reg_1132);

assign add_ln813_21_fu_899_p2 = (add_ln813_20_fu_894_p2 + add_ln813_18_fu_883_p2);

assign add_ln813_22_fu_905_p2 = (add_ln813_21_fu_899_p2 + add_ln813_17_fu_879_p2);

assign add_ln813_23_fu_663_p2 = ($signed(grp_fu_495_p4) + $signed(sext_ln818_2_fu_653_p1));

assign add_ln813_24_fu_775_p2 = ($signed(grp_fu_485_p4) + $signed(sext_ln818_4_fu_759_p1));

assign add_ln813_25_fu_911_p2 = (add_ln813_24_reg_1077 + add_ln813_23_reg_1041);

assign add_ln813_26_fu_915_p2 = (reg_543 + trunc_ln818_21_reg_1112);

assign add_ln813_27_fu_920_p2 = (grp_fu_515_p4 + 16'd195);

assign add_ln813_28_fu_926_p2 = (add_ln813_27_fu_920_p2 + trunc_ln818_25_reg_1137);

assign add_ln813_29_fu_931_p2 = (add_ln813_28_fu_926_p2 + add_ln813_26_fu_915_p2);

assign add_ln813_30_fu_937_p2 = (add_ln813_29_fu_931_p2 + add_ln813_25_fu_911_p2);

assign add_ln813_31_fu_689_p2 = (reg_539 + grp_fu_495_p4);

assign add_ln813_32_fu_788_p2 = (reg_547 + grp_fu_485_p4);

assign add_ln813_33_fu_967_p2 = (add_ln813_32_reg_1087 + add_ln813_31_reg_1057);

assign add_ln813_34_fu_971_p2 = ($signed(sext_ln818_5_fu_943_p1) + $signed(sext_ln818_7_fu_946_p1));

assign add_ln813_35_fu_977_p2 = ($signed(sext_ln813_fu_963_p1) + $signed(14'd229));

assign add_ln813_36_fu_987_p2 = ($signed(sext_ln813_1_fu_983_p1) + $signed(reg_535));

assign add_ln813_37_fu_993_p2 = (add_ln813_36_fu_987_p2 + add_ln813_34_fu_971_p2);

assign add_ln813_38_fu_999_p2 = (add_ln813_37_fu_993_p2 + add_ln813_33_fu_967_p2);

assign add_ln813_8_fu_763_p2 = (reg_539 + grp_fu_505_p4);

assign add_ln813_9_fu_846_p2 = (add_ln813_8_reg_1067 + add_ln813_reg_1036);

assign add_ln813_fu_657_p2 = ($signed(sext_ln818_fu_598_p1) + $signed(grp_fu_515_p4));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_return_0 = add_ln813_14_reg_1147;

assign ap_return_1 = add_ln813_22_reg_1152;

assign ap_return_2 = add_ln813_30_reg_1157;

assign ap_return_3 = add_ln813_38_fu_999_p2;

assign grp_fu_485_p4 = {{grp_fu_189_p2[25:10]}};

assign grp_fu_495_p4 = {{grp_fu_191_p2[25:10]}};

assign grp_fu_505_p4 = {{grp_fu_188_p2[25:10]}};

assign grp_fu_515_p4 = {{grp_fu_190_p2[25:10]}};

assign grp_fu_525_p1 = grp_fu_189_p2;

assign grp_fu_525_p4 = {{grp_fu_525_p1[23:10]}};

assign r_V_11_fu_743_p2 = ($signed(sext_ln1273_4_fu_727_p1) + $signed(sext_ln1273_5_fu_739_p1));

assign r_V_7_fu_637_p2 = ($signed(sub_ln1273_fu_619_p2) - $signed(sext_ln1273_3_fu_633_p1));

assign r_V_fu_582_p2 = ($signed(sext_ln1273_fu_566_p1) - $signed(sext_ln1273_1_fu_578_p1));

assign sext_ln1270_2_fu_695_p0 = ap_port_reg_p_read3;

assign sext_ln1270_2_fu_695_p1 = sext_ln1270_2_fu_695_p0;

assign sext_ln1270_3_fu_781_p0 = ap_port_reg_p_read4;

assign sext_ln1270_3_fu_781_p1 = sext_ln1270_3_fu_781_p0;

assign sext_ln1270_4_fu_808_p0 = ap_port_reg_p_read5;

assign sext_ln1270_4_fu_808_p1 = sext_ln1270_4_fu_808_p0;

assign sext_ln1270_fu_677_p1 = $signed(ap_port_reg_p_read2);

assign sext_ln1273_1_fu_578_p1 = $signed(shl_ln1273_1_fu_570_p3);

assign sext_ln1273_2_fu_615_p1 = $signed(shl_ln1273_2_fu_607_p3);

assign sext_ln1273_3_fu_633_p1 = $signed(shl_ln1273_3_fu_625_p3);

assign sext_ln1273_4_fu_727_p1 = $signed(shl_ln1273_4_fu_719_p3);

assign sext_ln1273_5_fu_739_p1 = $signed(shl_ln1273_5_fu_731_p3);

assign sext_ln1273_fu_566_p1 = $signed(shl_ln_fu_558_p3);

assign sext_ln70_1_fu_669_p1 = p_read19_reg_1026;

assign sext_ln70_2_fu_602_p0 = p_read1;

assign sext_ln70_2_fu_602_p1 = sext_ln70_2_fu_602_p0;

assign sext_ln70_3_fu_700_p0 = ap_port_reg_p_read3;

assign sext_ln70_3_fu_700_p1 = sext_ln70_3_fu_700_p0;

assign sext_ln70_4_fu_794_p1 = p_read412_reg_1082;

assign sext_ln70_5_fu_814_p0 = ap_port_reg_p_read5;

assign sext_ln70_5_fu_814_p1 = sext_ln70_5_fu_814_p0;

assign sext_ln70_6_fu_829_p1 = $signed(ap_port_reg_p_read6);

assign sext_ln70_7_fu_949_p1 = p_read715_reg_1142;

assign sext_ln70_8_fu_839_p0 = ap_port_reg_p_read7;

assign sext_ln70_8_fu_839_p1 = sext_ln70_8_fu_839_p0;

assign sext_ln70_fu_551_p0 = p_read;

assign sext_ln70_fu_551_p1 = sext_ln70_fu_551_p0;

assign sext_ln813_1_fu_983_p1 = $signed(add_ln813_35_fu_977_p2);

assign sext_ln813_fu_963_p1 = $signed(trunc_ln818_30_fu_953_p4);

assign sext_ln818_1_fu_673_p1 = $signed(grp_fu_525_p4);

assign sext_ln818_2_fu_653_p1 = $signed(trunc_ln818_4_fu_643_p4);

assign sext_ln818_3_fu_715_p1 = $signed(trunc_ln818_12_fu_705_p4);

assign sext_ln818_4_fu_759_p1 = $signed(trunc_ln818_13_fu_749_p4);

assign sext_ln818_5_fu_943_p1 = $signed(trunc_ln818_18_reg_1092);

assign sext_ln818_6_fu_836_p1 = $signed(trunc_ln818_19_reg_1102);

assign sext_ln818_7_fu_946_p1 = $signed(trunc_ln818_22_reg_1117);

assign sext_ln818_fu_598_p1 = $signed(trunc_ln_fu_588_p4);

assign shl_ln1273_1_fu_570_p1 = p_read;

assign shl_ln1273_1_fu_570_p3 = {{shl_ln1273_1_fu_570_p1}, {2'd0}};

assign shl_ln1273_2_fu_607_p1 = p_read1;

assign shl_ln1273_2_fu_607_p3 = {{shl_ln1273_2_fu_607_p1}, {8'd0}};

assign shl_ln1273_3_fu_625_p1 = p_read1;

assign shl_ln1273_3_fu_625_p3 = {{shl_ln1273_3_fu_625_p1}, {1'd0}};

assign shl_ln1273_4_fu_719_p1 = ap_port_reg_p_read3;

assign shl_ln1273_4_fu_719_p3 = {{shl_ln1273_4_fu_719_p1}, {8'd0}};

assign shl_ln1273_5_fu_731_p1 = ap_port_reg_p_read3;

assign shl_ln1273_5_fu_731_p3 = {{shl_ln1273_5_fu_731_p1}, {4'd0}};

assign shl_ln_fu_558_p1 = p_read;

assign shl_ln_fu_558_p3 = {{shl_ln_fu_558_p1}, {6'd0}};

assign sub_ln1273_fu_619_p2 = ($signed(25'd0) - $signed(sext_ln1273_2_fu_615_p1));

assign trunc_ln818_12_fu_705_p1 = grp_fu_190_p2;

assign trunc_ln818_12_fu_705_p4 = {{trunc_ln818_12_fu_705_p1[24:10]}};

assign trunc_ln818_13_fu_749_p4 = {{r_V_11_fu_743_p2[24:10]}};

assign trunc_ln818_18_fu_798_p1 = grp_fu_189_p2;

assign trunc_ln818_19_fu_819_p1 = grp_fu_191_p2;

assign trunc_ln818_30_fu_953_p1 = grp_fu_189_p2;

assign trunc_ln818_30_fu_953_p4 = {{trunc_ln818_30_fu_953_p1[22:10]}};

assign trunc_ln818_4_fu_643_p4 = {{r_V_7_fu_637_p2[24:10]}};

assign trunc_ln_fu_588_p4 = {{r_V_fu_582_p2[22:10]}};

endmodule //myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config5_s
