// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_bincls_axilite_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);


output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;

wire   [0:0] icmp_ln1649_fu_112_p2;
wire   [14:0] trunc_ln40_10_fu_108_p1;
wire   [14:0] datareg_V_fu_118_p3;
wire   [0:0] icmp_ln1649_4_fu_130_p2;
wire   [14:0] trunc_ln40_9_fu_104_p1;
wire   [14:0] datareg_V_4_fu_136_p3;
wire   [0:0] icmp_ln1649_5_fu_148_p2;
wire   [14:0] trunc_ln40_8_fu_100_p1;
wire   [14:0] datareg_V_5_fu_154_p3;
wire   [0:0] icmp_ln1649_6_fu_166_p2;
wire   [14:0] trunc_ln40_7_fu_96_p1;
wire   [14:0] datareg_V_6_fu_172_p3;
wire   [0:0] icmp_ln1649_7_fu_184_p2;
wire   [14:0] trunc_ln40_6_fu_92_p1;
wire   [14:0] datareg_V_7_fu_190_p3;
wire   [0:0] icmp_ln1649_8_fu_202_p2;
wire   [14:0] trunc_ln40_5_fu_88_p1;
wire   [14:0] datareg_V_8_fu_208_p3;
wire   [0:0] icmp_ln1649_9_fu_220_p2;
wire   [14:0] trunc_ln40_4_fu_84_p1;
wire   [14:0] datareg_V_9_fu_226_p3;
wire   [0:0] icmp_ln1649_10_fu_238_p2;
wire   [14:0] trunc_ln40_fu_80_p1;
wire   [14:0] datareg_V_10_fu_244_p3;
wire   [15:0] zext_ln45_fu_126_p1;
wire   [15:0] zext_ln45_4_fu_144_p1;
wire   [15:0] zext_ln45_5_fu_162_p1;
wire   [15:0] zext_ln45_6_fu_180_p1;
wire   [15:0] zext_ln45_7_fu_198_p1;
wire   [15:0] zext_ln45_8_fu_216_p1;
wire   [15:0] zext_ln45_9_fu_234_p1;
wire   [15:0] zext_ln45_10_fu_252_p1;

assign ap_ready = 1'b1;

assign datareg_V_10_fu_244_p3 = ((icmp_ln1649_10_fu_238_p2[0:0] == 1'b1) ? trunc_ln40_fu_80_p1 : 15'd0);

assign datareg_V_4_fu_136_p3 = ((icmp_ln1649_4_fu_130_p2[0:0] == 1'b1) ? trunc_ln40_9_fu_104_p1 : 15'd0);

assign datareg_V_5_fu_154_p3 = ((icmp_ln1649_5_fu_148_p2[0:0] == 1'b1) ? trunc_ln40_8_fu_100_p1 : 15'd0);

assign datareg_V_6_fu_172_p3 = ((icmp_ln1649_6_fu_166_p2[0:0] == 1'b1) ? trunc_ln40_7_fu_96_p1 : 15'd0);

assign datareg_V_7_fu_190_p3 = ((icmp_ln1649_7_fu_184_p2[0:0] == 1'b1) ? trunc_ln40_6_fu_92_p1 : 15'd0);

assign datareg_V_8_fu_208_p3 = ((icmp_ln1649_8_fu_202_p2[0:0] == 1'b1) ? trunc_ln40_5_fu_88_p1 : 15'd0);

assign datareg_V_9_fu_226_p3 = ((icmp_ln1649_9_fu_220_p2[0:0] == 1'b1) ? trunc_ln40_4_fu_84_p1 : 15'd0);

assign datareg_V_fu_118_p3 = ((icmp_ln1649_fu_112_p2[0:0] == 1'b1) ? trunc_ln40_10_fu_108_p1 : 15'd0);

assign trunc_ln40_10_fu_108_p1 = p_read[14:0];

assign trunc_ln40_4_fu_84_p1 = p_read6[14:0];

assign trunc_ln40_5_fu_88_p1 = p_read5[14:0];

assign trunc_ln40_6_fu_92_p1 = p_read4[14:0];

assign trunc_ln40_7_fu_96_p1 = p_read3[14:0];

assign trunc_ln40_8_fu_100_p1 = p_read2[14:0];

assign trunc_ln40_9_fu_104_p1 = p_read1[14:0];

assign trunc_ln40_fu_80_p1 = p_read7[14:0];

assign zext_ln45_10_fu_252_p1 = datareg_V_10_fu_244_p3;

assign zext_ln45_4_fu_144_p1 = datareg_V_4_fu_136_p3;

assign zext_ln45_5_fu_162_p1 = datareg_V_5_fu_154_p3;

assign zext_ln45_6_fu_180_p1 = datareg_V_6_fu_172_p3;

assign zext_ln45_7_fu_198_p1 = datareg_V_7_fu_190_p3;

assign zext_ln45_8_fu_216_p1 = datareg_V_8_fu_208_p3;

assign zext_ln45_9_fu_234_p1 = datareg_V_9_fu_226_p3;

assign zext_ln45_fu_126_p1 = datareg_V_fu_118_p3;

assign ap_return_0 = zext_ln45_fu_126_p1;

assign ap_return_1 = zext_ln45_4_fu_144_p1;

assign ap_return_2 = zext_ln45_5_fu_162_p1;

assign ap_return_3 = zext_ln45_6_fu_180_p1;

assign ap_return_4 = zext_ln45_7_fu_198_p1;

assign ap_return_5 = zext_ln45_8_fu_216_p1;

assign ap_return_6 = zext_ln45_9_fu_234_p1;

assign ap_return_7 = zext_ln45_10_fu_252_p1;

assign icmp_ln1649_10_fu_238_p2 = (($signed(p_read7) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_4_fu_130_p2 = (($signed(p_read1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_5_fu_148_p2 = (($signed(p_read2) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_6_fu_166_p2 = (($signed(p_read3) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_7_fu_184_p2 = (($signed(p_read4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_8_fu_202_p2 = (($signed(p_read5) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_9_fu_220_p2 = (($signed(p_read6) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_fu_112_p2 = (($signed(p_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_bincls_axilite_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s
