// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] grp_fu_359_p4;
reg   [15:0] reg_389;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state12;
wire   [15:0] grp_fu_369_p4;
reg   [15:0] reg_393;
wire    ap_CS_fsm_state4;
reg   [15:0] reg_397;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state11;
wire  signed [25:0] sext_ln70_fu_401_p1;
reg  signed [25:0] sext_ln70_reg_925;
reg   [11:0] trunc_ln818_1_reg_930;
reg  signed [15:0] p_read19_reg_935;
wire   [15:0] add_ln813_fu_452_p2;
reg   [15:0] add_ln813_reg_940;
wire  signed [23:0] sext_ln70_2_fu_458_p1;
reg  signed [23:0] sext_ln70_2_reg_945;
wire    ap_CS_fsm_state3;
wire   [15:0] add_ln813_15_fu_481_p2;
reg   [15:0] add_ln813_15_reg_950;
wire   [15:0] add_ln813_23_fu_487_p2;
reg   [15:0] add_ln813_23_reg_955;
wire  signed [25:0] sext_ln70_3_fu_500_p1;
reg  signed [25:0] sext_ln70_3_reg_960;
reg   [12:0] trunc_ln818_7_reg_966;
wire   [14:0] add_ln813_31_fu_545_p2;
reg   [14:0] add_ln813_31_reg_971;
reg  signed [15:0] p_read311_reg_976;
wire    ap_CS_fsm_state6;
wire  signed [25:0] sext_ln70_4_fu_554_p1;
reg  signed [25:0] sext_ln70_4_reg_981;
wire   [15:0] add_ln813_8_fu_560_p2;
reg   [15:0] add_ln813_8_reg_986;
wire   [15:0] add_ln813_16_fu_566_p2;
reg   [15:0] add_ln813_16_reg_991;
wire   [15:0] add_ln813_24_fu_580_p2;
reg   [15:0] add_ln813_24_reg_996;
wire    ap_CS_fsm_state7;
wire   [15:0] add_ln813_32_fu_586_p2;
reg   [15:0] add_ln813_32_reg_1001;
wire  signed [25:0] sext_ln70_6_fu_592_p1;
reg  signed [25:0] sext_ln70_6_reg_1006;
reg   [12:0] trunc_ln818_17_reg_1011;
reg  signed [15:0] p_read513_reg_1016;
reg   [15:0] trunc_ln818_18_reg_1022;
wire  signed [25:0] sext_ln70_7_fu_644_p1;
reg  signed [25:0] sext_ln70_7_reg_1027;
reg   [15:0] trunc_ln818_20_reg_1033;
wire    ap_CS_fsm_state10;
reg   [15:0] trunc_ln818_21_reg_1038;
reg  signed [15:0] p_read715_reg_1043;
reg  signed [15:0] p_read614_reg_1048;
wire  signed [25:0] sext_ln1270_2_fu_649_p1;
reg  signed [25:0] sext_ln1270_2_reg_1054;
wire   [15:0] add_ln813_14_fu_719_p2;
reg   [15:0] add_ln813_14_reg_1059;
wire  signed [25:0] sext_ln1270_3_fu_759_p1;
reg  signed [25:0] sext_ln1270_3_reg_1064;
wire   [15:0] add_ln813_22_fu_790_p2;
reg   [15:0] add_ln813_22_reg_1070;
reg   [15:0] ap_port_reg_p_read1;
reg   [15:0] ap_port_reg_p_read2;
reg   [15:0] ap_port_reg_p_read3;
reg   [15:0] ap_port_reg_p_read4;
reg   [15:0] ap_port_reg_p_read5;
reg   [15:0] ap_port_reg_p_read6;
reg   [15:0] ap_port_reg_p_read7;
reg  signed [15:0] grp_fu_184_p0;
wire  signed [23:0] sext_ln70_5_fu_572_p1;
reg  signed [12:0] grp_fu_184_p1;
wire    ap_CS_fsm_state13;
reg  signed [15:0] grp_fu_185_p0;
wire  signed [25:0] sext_ln1270_fu_447_p1;
reg  signed [12:0] grp_fu_185_p1;
wire   [25:0] grp_fu_184_p2;
wire   [25:0] grp_fu_185_p2;
wire   [23:0] grp_fu_379_p1;
wire  signed [15:0] sext_ln70_fu_401_p0;
wire  signed [15:0] shl_ln_fu_407_p1;
wire   [20:0] shl_ln_fu_407_p3;
wire  signed [15:0] shl_ln1273_2_fu_419_p1;
wire   [17:0] shl_ln1273_2_fu_419_p3;
wire  signed [21:0] sext_ln1273_2_fu_427_p1;
wire  signed [21:0] sext_ln1273_fu_415_p1;
wire   [21:0] r_V_5_fu_431_p2;
wire  signed [15:0] sext_ln1270_fu_447_p0;
wire   [13:0] grp_fu_379_p4;
wire   [23:0] trunc_ln818_4_fu_467_p1;
wire   [13:0] trunc_ln818_4_fu_467_p4;
wire  signed [15:0] sext_ln818_fu_463_p1;
wire  signed [15:0] sext_ln818_1_fu_477_p1;
wire  signed [15:0] sext_ln70_3_fu_500_p0;
wire  signed [15:0] shl_ln1273_3_fu_505_p1;
wire   [21:0] shl_ln1273_3_fu_505_p3;
wire  signed [15:0] shl_ln1273_4_fu_517_p1;
wire   [17:0] shl_ln1273_4_fu_517_p3;
wire  signed [22:0] sext_ln1273_3_fu_513_p1;
wire  signed [22:0] sext_ln1273_4_fu_525_p1;
wire   [22:0] r_V_9_fu_529_p2;
wire  signed [14:0] sext_ln70_8_fu_493_p1;
wire  signed [14:0] sext_ln70_9_fu_496_p1;
wire  signed [15:0] sext_ln70_4_fu_554_p0;
wire  signed [15:0] sext_ln818_2_fu_551_p1;
wire  signed [15:0] sext_ln818_3_fu_576_p1;
wire  signed [15:0] sext_ln70_6_fu_592_p0;
wire  signed [15:0] shl_ln1273_5_fu_598_p1;
wire   [21:0] shl_ln1273_5_fu_598_p3;
wire  signed [22:0] sext_ln1273_5_fu_606_p1;
wire  signed [15:0] shl_ln1273_6_fu_616_p1;
wire   [18:0] shl_ln1273_6_fu_616_p3;
wire   [22:0] sub_ln1273_fu_610_p2;
wire  signed [22:0] sext_ln1273_6_fu_624_p1;
wire   [22:0] r_V_15_fu_628_p2;
wire  signed [15:0] sext_ln70_7_fu_644_p0;
wire  signed [15:0] sext_ln1270_2_fu_649_p0;
wire  signed [15:0] shl_ln1273_1_fu_655_p1;
wire  signed [15:0] shl_ln1273_10_fu_663_p1;
wire   [20:0] shl_ln1273_10_fu_663_p3;
wire  signed [25:0] sext_ln1273_9_fu_671_p1;
wire   [25:0] shl_ln1273_1_fu_655_p3;
wire   [25:0] r_V_20_fu_675_p2;
wire   [15:0] trunc_ln818_27_fu_681_p4;
wire   [15:0] add_ln813_11_fu_701_p2;
wire   [15:0] add_ln813_12_fu_707_p2;
wire   [15:0] add_ln813_10_fu_695_p2;
wire   [15:0] add_ln813_13_fu_713_p2;
wire   [15:0] add_ln813_9_fu_691_p2;
wire   [23:0] shl_ln1273_s_fu_732_p3;
wire   [25:0] shl_ln1273_9_fu_725_p3;
wire  signed [25:0] sext_ln1273_8_fu_739_p1;
wire   [25:0] r_V_19_fu_743_p2;
wire   [15:0] add_ln813_19_fu_772_p2;
wire   [15:0] trunc_ln818_24_fu_749_p4;
wire   [15:0] add_ln813_20_fu_778_p2;
wire   [15:0] add_ln813_18_fu_767_p2;
wire   [15:0] add_ln813_21_fu_784_p2;
wire   [15:0] add_ln813_17_fu_763_p2;
wire   [20:0] shl_ln1273_8_fu_806_p3;
wire   [25:0] shl_ln1273_7_fu_799_p3;
wire  signed [25:0] sext_ln1273_7_fu_813_p1;
wire   [25:0] r_V_18_fu_817_p2;
wire  signed [15:0] sext_ln818_4_fu_796_p1;
wire   [15:0] add_ln813_27_fu_842_p2;
wire   [15:0] add_ln813_28_fu_848_p2;
wire   [15:0] add_ln813_26_fu_837_p2;
wire   [15:0] add_ln813_29_fu_854_p2;
wire   [15:0] add_ln813_25_fu_833_p2;
wire  signed [15:0] sext_ln813_fu_866_p1;
wire   [15:0] trunc_ln818_22_fu_823_p4;
wire   [15:0] add_ln813_35_fu_879_p2;
wire   [15:0] add_ln813_36_fu_885_p2;
wire   [15:0] add_ln813_34_fu_874_p2;
wire   [15:0] add_ln813_37_fu_891_p2;
wire   [15:0] add_ln813_33_fu_869_p2;
wire   [15:0] add_ln813_30_fu_860_p2;
wire   [15:0] add_ln813_38_fu_897_p2;
reg   [12:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
end

myproject_bincls_axilite_mul_16s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_1_1_U258(
    .din0(grp_fu_184_p0),
    .din1(grp_fu_184_p1),
    .dout(grp_fu_184_p2)
);

myproject_bincls_axilite_mul_16s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_1_1_U259(
    .din0(grp_fu_185_p0),
    .din1(grp_fu_185_p1),
    .dout(grp_fu_185_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        add_ln813_14_reg_1059 <= add_ln813_14_fu_719_p2;
        p_read614_reg_1048 <= ap_port_reg_p_read6;
        p_read715_reg_1043 <= ap_port_reg_p_read7;
        sext_ln1270_2_reg_1054 <= sext_ln1270_2_fu_649_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln813_15_reg_950 <= add_ln813_15_fu_481_p2;
        add_ln813_23_reg_955 <= add_ln813_23_fu_487_p2;
        sext_ln70_2_reg_945 <= sext_ln70_2_fu_458_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln813_16_reg_991 <= add_ln813_16_fu_566_p2;
        add_ln813_8_reg_986 <= add_ln813_8_fu_560_p2;
        p_read311_reg_976 <= ap_port_reg_p_read3;
        sext_ln70_4_reg_981 <= sext_ln70_4_fu_554_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        add_ln813_22_reg_1070 <= add_ln813_22_fu_790_p2;
        sext_ln1270_3_reg_1064 <= sext_ln1270_3_fu_759_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln813_24_reg_996 <= add_ln813_24_fu_580_p2;
        add_ln813_32_reg_1001 <= add_ln813_32_fu_586_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln813_31_reg_971 <= add_ln813_31_fu_545_p2;
        sext_ln70_3_reg_960 <= sext_ln70_3_fu_500_p1;
        trunc_ln818_7_reg_966 <= {{r_V_9_fu_529_p2[22:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln813_reg_940 <= add_ln813_fu_452_p2;
        p_read19_reg_935 <= ap_port_reg_p_read1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ap_port_reg_p_read1 <= p_read1;
        ap_port_reg_p_read2 <= p_read2;
        ap_port_reg_p_read3 <= p_read3;
        ap_port_reg_p_read4 <= p_read4;
        ap_port_reg_p_read5 <= p_read5;
        ap_port_reg_p_read6 <= p_read6;
        ap_port_reg_p_read7 <= p_read7;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        p_read513_reg_1016 <= ap_port_reg_p_read5;
        sext_ln70_7_reg_1027 <= sext_ln70_7_fu_644_p1;
        trunc_ln818_18_reg_1022 <= {{grp_fu_184_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        reg_389 <= {{grp_fu_184_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state1))) begin
        reg_393 <= {{grp_fu_185_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5))) begin
        reg_397 <= {{grp_fu_185_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        sext_ln70_6_reg_1006 <= sext_ln70_6_fu_592_p1;
        trunc_ln818_17_reg_1011 <= {{r_V_15_fu_628_p2[22:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sext_ln70_reg_925 <= sext_ln70_fu_401_p1;
        trunc_ln818_1_reg_930 <= {{r_V_5_fu_431_p2[21:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        trunc_ln818_20_reg_1033 <= {{grp_fu_184_p2[25:10]}};
        trunc_ln818_21_reg_1038 <= {{grp_fu_185_p2[25:10]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_184_p0 = sext_ln1270_3_reg_1064;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_184_p0 = sext_ln1270_2_reg_1054;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_184_p0 = sext_ln1270_2_fu_649_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_184_p0 = sext_ln70_7_reg_1027;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_184_p0 = sext_ln70_6_reg_1006;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_184_p0 = sext_ln70_6_fu_592_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_184_p0 = sext_ln70_5_fu_572_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_184_p0 = sext_ln70_4_fu_554_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_184_p0 = sext_ln70_3_reg_960;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_184_p0 = sext_ln70_2_reg_945;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_184_p0 = sext_ln70_2_fu_458_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_184_p0 = sext_ln70_reg_925;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_184_p0 = sext_ln70_fu_401_p1;
    end else begin
        grp_fu_184_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_184_p1 = 26'd604;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_184_p1 = 26'd1347;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_184_p1 = 26'd67108015;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_184_p1 = 26'd641;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_184_p1 = 26'd313;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_184_p1 = 26'd419;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_184_p1 = 24'd16777132;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_184_p1 = 26'd697;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_184_p1 = 26'd325;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_184_p1 = 24'd93;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_184_p1 = 24'd16777093;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_184_p1 = 26'd309;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_184_p1 = 26'd940;
    end else begin
        grp_fu_184_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_185_p0 = sext_ln1270_3_reg_1064;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_185_p0 = sext_ln1270_3_fu_759_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_185_p0 = sext_ln1270_2_fu_649_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_185_p0 = sext_ln70_7_reg_1027;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_185_p0 = sext_ln70_7_fu_644_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_185_p0 = sext_ln70_6_fu_592_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_185_p0 = sext_ln70_4_reg_981;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_185_p0 = sext_ln70_4_fu_554_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_185_p0 = sext_ln70_3_reg_960;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_185_p0 = sext_ln70_3_fu_500_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_185_p0 = sext_ln70_2_fu_458_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_185_p0 = sext_ln1270_fu_447_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_185_p0 = sext_ln70_fu_401_p1;
    end else begin
        grp_fu_185_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_185_p1 = 26'd1161;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_185_p1 = 26'd870;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_185_p1 = 26'd67108293;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_185_p1 = 26'd67108563;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_185_p1 = 26'd67108566;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_185_p1 = 26'd67108579;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_185_p1 = 26'd67108308;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_185_p1 = 26'd67108334;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_185_p1 = 26'd772;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_185_p1 = 24'd76;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_185_p1 = 26'd731;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_185_p1 = 26'd619;
    end else begin
        grp_fu_185_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln813_10_fu_695_p2 = (reg_389 + reg_397);

assign add_ln813_11_fu_701_p2 = (trunc_ln818_27_fu_681_p4 + 16'd376);

assign add_ln813_12_fu_707_p2 = (add_ln813_11_fu_701_p2 + grp_fu_359_p4);

assign add_ln813_13_fu_713_p2 = (add_ln813_12_fu_707_p2 + add_ln813_10_fu_695_p2);

assign add_ln813_14_fu_719_p2 = (add_ln813_13_fu_713_p2 + add_ln813_9_fu_691_p2);

assign add_ln813_15_fu_481_p2 = ($signed(reg_393) + $signed(sext_ln818_fu_463_p1));

assign add_ln813_16_fu_566_p2 = ($signed(sext_ln818_2_fu_551_p1) + $signed(grp_fu_369_p4));

assign add_ln813_17_fu_763_p2 = (add_ln813_16_reg_991 + add_ln813_15_reg_950);

assign add_ln813_18_fu_767_p2 = (reg_393 + trunc_ln818_20_reg_1033);

assign add_ln813_19_fu_772_p2 = (grp_fu_369_p4 + 16'd70);

assign add_ln813_20_fu_778_p2 = (add_ln813_19_fu_772_p2 + trunc_ln818_24_fu_749_p4);

assign add_ln813_21_fu_784_p2 = (add_ln813_20_fu_778_p2 + add_ln813_18_fu_767_p2);

assign add_ln813_22_fu_790_p2 = (add_ln813_21_fu_784_p2 + add_ln813_17_fu_763_p2);

assign add_ln813_23_fu_487_p2 = ($signed(reg_389) + $signed(sext_ln818_1_fu_477_p1));

assign add_ln813_24_fu_580_p2 = ($signed(reg_389) + $signed(sext_ln818_3_fu_576_p1));

assign add_ln813_25_fu_833_p2 = (add_ln813_24_reg_996 + add_ln813_23_reg_955);

assign add_ln813_26_fu_837_p2 = ($signed(sext_ln818_4_fu_796_p1) + $signed(trunc_ln818_21_reg_1038));

assign add_ln813_27_fu_842_p2 = ($signed(grp_fu_359_p4) + $signed(16'd65498));

assign add_ln813_28_fu_848_p2 = (add_ln813_27_fu_842_p2 + reg_397);

assign add_ln813_29_fu_854_p2 = (add_ln813_28_fu_848_p2 + add_ln813_26_fu_837_p2);

assign add_ln813_30_fu_860_p2 = (add_ln813_29_fu_854_p2 + add_ln813_25_fu_833_p2);

assign add_ln813_31_fu_545_p2 = ($signed(sext_ln70_8_fu_493_p1) + $signed(sext_ln70_9_fu_496_p1));

assign add_ln813_32_fu_586_p2 = (reg_397 + grp_fu_369_p4);

assign add_ln813_33_fu_869_p2 = ($signed(add_ln813_32_reg_1001) + $signed(sext_ln813_fu_866_p1));

assign add_ln813_34_fu_874_p2 = (trunc_ln818_18_reg_1022 + trunc_ln818_22_fu_823_p4);

assign add_ln813_35_fu_879_p2 = ($signed(grp_fu_369_p4) + $signed(16'd65420));

assign add_ln813_36_fu_885_p2 = (add_ln813_35_fu_879_p2 + reg_389);

assign add_ln813_37_fu_891_p2 = (add_ln813_36_fu_885_p2 + add_ln813_34_fu_874_p2);

assign add_ln813_38_fu_897_p2 = (add_ln813_37_fu_891_p2 + add_ln813_33_fu_869_p2);

assign add_ln813_8_fu_560_p2 = (reg_393 + grp_fu_359_p4);

assign add_ln813_9_fu_691_p2 = (add_ln813_8_reg_986 + add_ln813_reg_940);

assign add_ln813_fu_452_p2 = (reg_389 + grp_fu_369_p4);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return_0 = add_ln813_14_reg_1059;

assign ap_return_1 = add_ln813_22_reg_1070;

assign ap_return_2 = add_ln813_30_fu_860_p2;

assign ap_return_3 = add_ln813_38_fu_897_p2;

assign grp_fu_359_p4 = {{grp_fu_184_p2[25:10]}};

assign grp_fu_369_p4 = {{grp_fu_185_p2[25:10]}};

assign grp_fu_379_p1 = grp_fu_184_p2;

assign grp_fu_379_p4 = {{grp_fu_379_p1[23:10]}};

assign r_V_15_fu_628_p2 = ($signed(sub_ln1273_fu_610_p2) - $signed(sext_ln1273_6_fu_624_p1));

assign r_V_18_fu_817_p2 = ($signed(shl_ln1273_7_fu_799_p3) - $signed(sext_ln1273_7_fu_813_p1));

assign r_V_19_fu_743_p2 = ($signed(shl_ln1273_9_fu_725_p3) - $signed(sext_ln1273_8_fu_739_p1));

assign r_V_20_fu_675_p2 = ($signed(sext_ln1273_9_fu_671_p1) - $signed(shl_ln1273_1_fu_655_p3));

assign r_V_5_fu_431_p2 = ($signed(sext_ln1273_2_fu_427_p1) - $signed(sext_ln1273_fu_415_p1));

assign r_V_9_fu_529_p2 = ($signed(sext_ln1273_3_fu_513_p1) + $signed(sext_ln1273_4_fu_525_p1));

assign sext_ln1270_2_fu_649_p0 = ap_port_reg_p_read6;

assign sext_ln1270_2_fu_649_p1 = sext_ln1270_2_fu_649_p0;

assign sext_ln1270_3_fu_759_p1 = p_read715_reg_1043;

assign sext_ln1270_fu_447_p0 = ap_port_reg_p_read1;

assign sext_ln1270_fu_447_p1 = sext_ln1270_fu_447_p0;

assign sext_ln1273_2_fu_427_p1 = $signed(shl_ln1273_2_fu_419_p3);

assign sext_ln1273_3_fu_513_p1 = $signed(shl_ln1273_3_fu_505_p3);

assign sext_ln1273_4_fu_525_p1 = $signed(shl_ln1273_4_fu_517_p3);

assign sext_ln1273_5_fu_606_p1 = $signed(shl_ln1273_5_fu_598_p3);

assign sext_ln1273_6_fu_624_p1 = $signed(shl_ln1273_6_fu_616_p3);

assign sext_ln1273_7_fu_813_p1 = $signed(shl_ln1273_8_fu_806_p3);

assign sext_ln1273_8_fu_739_p1 = $signed(shl_ln1273_s_fu_732_p3);

assign sext_ln1273_9_fu_671_p1 = $signed(shl_ln1273_10_fu_663_p3);

assign sext_ln1273_fu_415_p1 = $signed(shl_ln_fu_407_p3);

assign sext_ln70_2_fu_458_p1 = p_read19_reg_935;

assign sext_ln70_3_fu_500_p0 = ap_port_reg_p_read2;

assign sext_ln70_3_fu_500_p1 = sext_ln70_3_fu_500_p0;

assign sext_ln70_4_fu_554_p0 = ap_port_reg_p_read3;

assign sext_ln70_4_fu_554_p1 = sext_ln70_4_fu_554_p0;

assign sext_ln70_5_fu_572_p1 = p_read311_reg_976;

assign sext_ln70_6_fu_592_p0 = ap_port_reg_p_read4;

assign sext_ln70_6_fu_592_p1 = sext_ln70_6_fu_592_p0;

assign sext_ln70_7_fu_644_p0 = ap_port_reg_p_read5;

assign sext_ln70_7_fu_644_p1 = sext_ln70_7_fu_644_p0;

assign sext_ln70_8_fu_493_p1 = $signed(trunc_ln818_1_reg_930);

assign sext_ln70_9_fu_496_p1 = $signed(grp_fu_379_p4);

assign sext_ln70_fu_401_p0 = p_read;

assign sext_ln70_fu_401_p1 = sext_ln70_fu_401_p0;

assign sext_ln813_fu_866_p1 = $signed(add_ln813_31_reg_971);

assign sext_ln818_1_fu_477_p1 = $signed(trunc_ln818_4_fu_467_p4);

assign sext_ln818_2_fu_551_p1 = $signed(trunc_ln818_7_reg_966);

assign sext_ln818_3_fu_576_p1 = $signed(grp_fu_379_p4);

assign sext_ln818_4_fu_796_p1 = $signed(trunc_ln818_17_reg_1011);

assign sext_ln818_fu_463_p1 = $signed(grp_fu_379_p4);

assign shl_ln1273_10_fu_663_p1 = ap_port_reg_p_read7;

assign shl_ln1273_10_fu_663_p3 = {{shl_ln1273_10_fu_663_p1}, {5'd0}};

assign shl_ln1273_1_fu_655_p1 = ap_port_reg_p_read7;

assign shl_ln1273_1_fu_655_p3 = {{shl_ln1273_1_fu_655_p1}, {10'd0}};

assign shl_ln1273_2_fu_419_p1 = p_read;

assign shl_ln1273_2_fu_419_p3 = {{shl_ln1273_2_fu_419_p1}, {2'd0}};

assign shl_ln1273_3_fu_505_p1 = ap_port_reg_p_read2;

assign shl_ln1273_3_fu_505_p3 = {{shl_ln1273_3_fu_505_p1}, {6'd0}};

assign shl_ln1273_4_fu_517_p1 = ap_port_reg_p_read2;

assign shl_ln1273_4_fu_517_p3 = {{shl_ln1273_4_fu_517_p1}, {2'd0}};

assign shl_ln1273_5_fu_598_p1 = ap_port_reg_p_read4;

assign shl_ln1273_5_fu_598_p3 = {{shl_ln1273_5_fu_598_p1}, {6'd0}};

assign shl_ln1273_6_fu_616_p1 = ap_port_reg_p_read4;

assign shl_ln1273_6_fu_616_p3 = {{shl_ln1273_6_fu_616_p1}, {3'd0}};

assign shl_ln1273_7_fu_799_p3 = {{p_read513_reg_1016}, {10'd0}};

assign shl_ln1273_8_fu_806_p3 = {{p_read513_reg_1016}, {5'd0}};

assign shl_ln1273_9_fu_725_p3 = {{p_read614_reg_1048}, {10'd0}};

assign shl_ln1273_s_fu_732_p3 = {{p_read614_reg_1048}, {8'd0}};

assign shl_ln_fu_407_p1 = p_read;

assign shl_ln_fu_407_p3 = {{shl_ln_fu_407_p1}, {5'd0}};

assign sub_ln1273_fu_610_p2 = ($signed(23'd0) - $signed(sext_ln1273_5_fu_606_p1));

assign trunc_ln818_22_fu_823_p4 = {{r_V_18_fu_817_p2[25:10]}};

assign trunc_ln818_24_fu_749_p4 = {{r_V_19_fu_743_p2[25:10]}};

assign trunc_ln818_27_fu_681_p4 = {{r_V_20_fu_675_p2[25:10]}};

assign trunc_ln818_4_fu_467_p1 = grp_fu_185_p2;

assign trunc_ln818_4_fu_467_p4 = {{trunc_ln818_4_fu_467_p1[23:10]}};

endmodule //myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config4_s
