// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_bincls_axilite_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s (
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);


output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;

wire   [0:0] icmp_ln1649_fu_64_p2;
wire   [14:0] trunc_ln40_3_fu_60_p1;
wire   [14:0] datareg_V_fu_70_p3;
wire   [0:0] icmp_ln1649_1_fu_82_p2;
wire   [14:0] trunc_ln40_2_fu_56_p1;
wire   [14:0] datareg_V_1_fu_88_p3;
wire   [0:0] icmp_ln1649_2_fu_100_p2;
wire   [14:0] trunc_ln40_1_fu_52_p1;
wire   [14:0] datareg_V_2_fu_106_p3;
wire   [0:0] icmp_ln1649_3_fu_118_p2;
wire   [14:0] trunc_ln40_fu_48_p1;
wire   [14:0] datareg_V_3_fu_124_p3;
wire   [15:0] zext_ln45_fu_78_p1;
wire   [15:0] zext_ln45_1_fu_96_p1;
wire   [15:0] zext_ln45_2_fu_114_p1;
wire   [15:0] zext_ln45_3_fu_132_p1;

assign ap_ready = 1'b1;

assign datareg_V_1_fu_88_p3 = ((icmp_ln1649_1_fu_82_p2[0:0] == 1'b1) ? trunc_ln40_2_fu_56_p1 : 15'd0);

assign datareg_V_2_fu_106_p3 = ((icmp_ln1649_2_fu_100_p2[0:0] == 1'b1) ? trunc_ln40_1_fu_52_p1 : 15'd0);

assign datareg_V_3_fu_124_p3 = ((icmp_ln1649_3_fu_118_p2[0:0] == 1'b1) ? trunc_ln40_fu_48_p1 : 15'd0);

assign datareg_V_fu_70_p3 = ((icmp_ln1649_fu_64_p2[0:0] == 1'b1) ? trunc_ln40_3_fu_60_p1 : 15'd0);

assign trunc_ln40_1_fu_52_p1 = p_read2[14:0];

assign trunc_ln40_2_fu_56_p1 = p_read1[14:0];

assign trunc_ln40_3_fu_60_p1 = p_read[14:0];

assign trunc_ln40_fu_48_p1 = p_read3[14:0];

assign zext_ln45_1_fu_96_p1 = datareg_V_1_fu_88_p3;

assign zext_ln45_2_fu_114_p1 = datareg_V_2_fu_106_p3;

assign zext_ln45_3_fu_132_p1 = datareg_V_3_fu_124_p3;

assign zext_ln45_fu_78_p1 = datareg_V_fu_70_p3;

assign ap_return_0 = zext_ln45_fu_78_p1;

assign ap_return_1 = zext_ln45_1_fu_96_p1;

assign ap_return_2 = zext_ln45_2_fu_114_p1;

assign ap_return_3 = zext_ln45_3_fu_132_p1;

assign icmp_ln1649_1_fu_82_p2 = (($signed(p_read1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_2_fu_100_p2 = (($signed(p_read2) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_3_fu_118_p2 = (($signed(p_read3) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1649_fu_64_p2 = (($signed(p_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_bincls_axilite_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config5_s
