// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [25:0] sext_ln1270_fu_134_p1;
reg  signed [25:0] sext_ln1270_reg_207;
wire   [15:0] grp_fu_124_p4;
reg   [15:0] trunc_ln_reg_212;
reg   [15:0] trunc_ln818_2_reg_217;
wire    ap_CS_fsm_state2;
wire  signed [25:0] sext_ln1270_1_fu_139_p1;
reg  signed [25:0] sext_ln1270_1_reg_222;
wire    ap_CS_fsm_state3;
reg   [15:0] trunc_ln818_3_reg_227;
reg   [15:0] trunc_ln818_4_reg_232;
wire    ap_CS_fsm_state4;
wire  signed [25:0] sext_ln1273_fu_144_p1;
reg  signed [25:0] sext_ln1273_reg_237;
wire    ap_CS_fsm_state5;
reg   [15:0] trunc_ln818_5_reg_242;
reg   [15:0] trunc_ln818_6_reg_247;
wire    ap_CS_fsm_state6;
wire  signed [25:0] sext_ln70_fu_149_p1;
reg  signed [25:0] sext_ln70_reg_252;
wire    ap_CS_fsm_state7;
wire   [15:0] add_ln813_3_fu_169_p2;
reg   [15:0] add_ln813_3_reg_257;
reg   [15:0] ap_port_reg_p_read1;
reg   [15:0] ap_port_reg_p_read2;
reg   [15:0] ap_port_reg_p_read3;
reg  signed [15:0] grp_fu_76_p0;
reg  signed [11:0] grp_fu_76_p1;
wire    ap_CS_fsm_state8;
wire   [25:0] grp_fu_76_p2;
wire   [15:0] add_ln813_1_fu_158_p2;
wire   [15:0] add_ln813_2_fu_164_p2;
wire   [15:0] add_ln813_fu_154_p2;
wire   [15:0] add_ln813_5_fu_179_p2;
wire   [15:0] add_ln813_6_fu_185_p2;
wire   [15:0] add_ln813_4_fu_175_p2;
wire   [15:0] add_ln813_7_fu_190_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

myproject_bincls_axilite_mul_16s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_1_1_U357(
    .din0(grp_fu_76_p0),
    .din1(grp_fu_76_p1),
    .dout(grp_fu_76_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln813_3_reg_257 <= add_ln813_3_fu_169_p2;
        sext_ln70_reg_252 <= sext_ln70_fu_149_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ap_port_reg_p_read1 <= p_read1;
        ap_port_reg_p_read2 <= p_read2;
        ap_port_reg_p_read3 <= p_read3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        sext_ln1270_1_reg_222 <= sext_ln1270_1_fu_139_p1;
        trunc_ln818_3_reg_227 <= {{grp_fu_76_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sext_ln1270_reg_207 <= sext_ln1270_fu_134_p1;
        trunc_ln_reg_212 <= {{grp_fu_76_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        sext_ln1273_reg_237 <= sext_ln1273_fu_144_p1;
        trunc_ln818_5_reg_242 <= {{grp_fu_76_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln818_2_reg_217 <= {{grp_fu_76_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        trunc_ln818_4_reg_232 <= {{grp_fu_76_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        trunc_ln818_6_reg_247 <= {{grp_fu_76_p2[25:10]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_76_p0 = sext_ln70_reg_252;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_76_p0 = sext_ln70_fu_149_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_76_p0 = sext_ln1273_reg_237;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_76_p0 = sext_ln1273_fu_144_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_76_p0 = sext_ln1270_1_reg_222;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_76_p0 = sext_ln1270_1_fu_139_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_76_p0 = sext_ln1270_reg_207;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_76_p0 = sext_ln1270_fu_134_p1;
    end else begin
        grp_fu_76_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_76_p1 = 26'd67108506;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_76_p1 = 26'd506;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_76_p1 = 26'd67108229;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_76_p1 = 26'd951;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_76_p1 = 26'd555;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_76_p1 = 26'd67108379;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_76_p1 = 26'd687;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_76_p1 = 26'd67107765;
    end else begin
        grp_fu_76_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln813_1_fu_158_p2 = (grp_fu_124_p4 + 16'd206);

assign add_ln813_2_fu_164_p2 = (add_ln813_1_fu_158_p2 + trunc_ln818_5_reg_242);

assign add_ln813_3_fu_169_p2 = (add_ln813_2_fu_164_p2 + add_ln813_fu_154_p2);

assign add_ln813_4_fu_175_p2 = (trunc_ln818_2_reg_217 + trunc_ln818_4_reg_232);

assign add_ln813_5_fu_179_p2 = ($signed(grp_fu_124_p4) + $signed(16'd65329));

assign add_ln813_6_fu_185_p2 = (add_ln813_5_fu_179_p2 + trunc_ln818_6_reg_247);

assign add_ln813_7_fu_190_p2 = (add_ln813_6_fu_185_p2 + add_ln813_4_fu_175_p2);

assign add_ln813_fu_154_p2 = (trunc_ln_reg_212 + trunc_ln818_3_reg_227);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_return_0 = add_ln813_3_reg_257;

assign ap_return_1 = add_ln813_7_fu_190_p2;

assign grp_fu_124_p4 = {{grp_fu_76_p2[25:10]}};

assign sext_ln1270_1_fu_139_p1 = $signed(ap_port_reg_p_read1);

assign sext_ln1270_fu_134_p1 = $signed(p_read);

assign sext_ln1273_fu_144_p1 = $signed(ap_port_reg_p_read2);

assign sext_ln70_fu_149_p1 = $signed(ap_port_reg_p_read3);

endmodule //myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config7_s
