// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire  signed [25:0] sext_ln1273_fu_139_p1;
reg  signed [25:0] sext_ln1273_reg_265;
wire   [15:0] grp_fu_129_p4;
reg   [15:0] trunc_ln_reg_270;
reg   [15:0] trunc_ln818_2_reg_275;
wire    ap_CS_fsm_state2;
reg  signed [15:0] p_read15_reg_280;
wire    ap_CS_fsm_state3;
reg   [15:0] trunc_ln818_3_reg_286;
wire  signed [25:0] sext_ln70_fu_149_p1;
reg  signed [25:0] sext_ln70_reg_291;
wire    ap_CS_fsm_state4;
reg   [15:0] trunc_ln818_5_reg_296;
reg   [15:0] trunc_ln818_6_reg_301;
wire    ap_CS_fsm_state5;
reg  signed [15:0] p_read37_reg_306;
wire    ap_CS_fsm_state6;
wire   [15:0] add_ln813_3_fu_174_p2;
reg   [15:0] add_ln813_3_reg_311;
reg   [15:0] ap_port_reg_p_read1;
reg   [15:0] ap_port_reg_p_read2;
reg   [15:0] ap_port_reg_p_read3;
reg  signed [15:0] grp_fu_86_p0;
wire  signed [25:0] sext_ln1270_fu_144_p1;
wire  signed [25:0] sext_ln1270_1_fu_154_p1;
wire  signed [24:0] sext_ln70_1_fu_214_p1;
reg  signed [11:0] grp_fu_86_p1;
wire    ap_CS_fsm_state7;
wire   [25:0] grp_fu_86_p2;
wire  signed [15:0] sext_ln1270_fu_144_p0;
wire  signed [15:0] sext_ln1270_1_fu_154_p0;
wire   [15:0] add_ln813_1_fu_163_p2;
wire   [15:0] add_ln813_2_fu_169_p2;
wire   [15:0] add_ln813_fu_159_p2;
wire   [23:0] shl_ln1273_1_fu_187_p3;
wire   [25:0] shl_ln_fu_180_p3;
wire  signed [25:0] sext_ln1273_1_fu_194_p1;
wire   [25:0] r_V_fu_198_p2;
wire   [24:0] trunc_ln818_8_fu_218_p1;
wire   [14:0] trunc_ln818_8_fu_218_p4;
wire   [15:0] trunc_ln818_4_fu_204_p4;
wire  signed [15:0] sext_ln818_fu_228_p1;
wire   [15:0] add_ln813_5_fu_237_p2;
wire   [15:0] add_ln813_6_fu_243_p2;
wire   [15:0] add_ln813_4_fu_232_p2;
wire   [15:0] add_ln813_7_fu_248_p2;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
end

myproject_bincls_axilite_mul_16s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_1_1_U273(
    .din0(grp_fu_86_p0),
    .din1(grp_fu_86_p1),
    .dout(grp_fu_86_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln813_3_reg_311 <= add_ln813_3_fu_174_p2;
        p_read37_reg_306 <= ap_port_reg_p_read3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ap_port_reg_p_read1 <= p_read1;
        ap_port_reg_p_read2 <= p_read2;
        ap_port_reg_p_read3 <= p_read3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_read15_reg_280 <= ap_port_reg_p_read1;
        trunc_ln818_3_reg_286 <= {{grp_fu_86_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sext_ln1273_reg_265 <= sext_ln1273_fu_139_p1;
        trunc_ln_reg_270 <= {{grp_fu_86_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sext_ln70_reg_291 <= sext_ln70_fu_149_p1;
        trunc_ln818_5_reg_296 <= {{grp_fu_86_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln818_2_reg_275 <= {{grp_fu_86_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        trunc_ln818_6_reg_301 <= {{grp_fu_86_p2[25:10]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_86_p0 = sext_ln70_1_fu_214_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_86_p0 = sext_ln1270_1_fu_154_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_86_p0 = sext_ln70_reg_291;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_86_p0 = sext_ln70_fu_149_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_86_p0 = sext_ln1270_fu_144_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_86_p0 = sext_ln1273_reg_265;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_86_p0 = sext_ln1273_fu_139_p1;
    end else begin
        grp_fu_86_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_86_p1 = 25'd148;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_86_p1 = 26'd67108007;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_86_p1 = 26'd437;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_86_p1 = 26'd381;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_86_p1 = 26'd67107441;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_86_p1 = 26'd67108250;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_86_p1 = 26'd978;
    end else begin
        grp_fu_86_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln813_1_fu_163_p2 = (grp_fu_129_p4 + 16'd370);

assign add_ln813_2_fu_169_p2 = (add_ln813_1_fu_163_p2 + trunc_ln818_5_reg_296);

assign add_ln813_3_fu_174_p2 = (add_ln813_2_fu_169_p2 + add_ln813_fu_159_p2);

assign add_ln813_4_fu_232_p2 = (trunc_ln818_2_reg_275 + trunc_ln818_4_fu_204_p4);

assign add_ln813_5_fu_237_p2 = ($signed(sext_ln818_fu_228_p1) + $signed(16'd65165));

assign add_ln813_6_fu_243_p2 = (add_ln813_5_fu_237_p2 + trunc_ln818_6_reg_301);

assign add_ln813_7_fu_248_p2 = (add_ln813_6_fu_243_p2 + add_ln813_4_fu_232_p2);

assign add_ln813_fu_159_p2 = (trunc_ln_reg_270 + trunc_ln818_3_reg_286);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_return_0 = add_ln813_3_reg_311;

assign ap_return_1 = add_ln813_7_fu_248_p2;

assign grp_fu_129_p4 = {{grp_fu_86_p2[25:10]}};

assign r_V_fu_198_p2 = ($signed(shl_ln_fu_180_p3) - $signed(sext_ln1273_1_fu_194_p1));

assign sext_ln1270_1_fu_154_p0 = ap_port_reg_p_read3;

assign sext_ln1270_1_fu_154_p1 = sext_ln1270_1_fu_154_p0;

assign sext_ln1270_fu_144_p0 = ap_port_reg_p_read1;

assign sext_ln1270_fu_144_p1 = sext_ln1270_fu_144_p0;

assign sext_ln1273_1_fu_194_p1 = $signed(shl_ln1273_1_fu_187_p3);

assign sext_ln1273_fu_139_p1 = $signed(p_read);

assign sext_ln70_1_fu_214_p1 = p_read37_reg_306;

assign sext_ln70_fu_149_p1 = $signed(ap_port_reg_p_read2);

assign sext_ln818_fu_228_p1 = $signed(trunc_ln818_8_fu_218_p4);

assign shl_ln1273_1_fu_187_p3 = {{p_read15_reg_280}, {8'd0}};

assign shl_ln_fu_180_p3 = {{p_read15_reg_280}, {10'd0}};

assign trunc_ln818_4_fu_204_p4 = {{r_V_fu_198_p2[25:10]}};

assign trunc_ln818_8_fu_218_p1 = grp_fu_86_p2;

assign trunc_ln818_8_fu_218_p4 = {{trunc_ln818_8_fu_218_p1[24:10]}};

endmodule //myproject_bincls_axilite_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s
