// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_bincls_axilite_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_subdone;
wire   [9:0] exp_table_address0;
reg    exp_table_ce0;
wire   [16:0] exp_table_q0;
wire   [9:0] exp_table_address1;
reg    exp_table_ce1;
wire   [16:0] exp_table_q1;
wire   [9:0] invert_table_address0;
reg    invert_table_ce0;
wire   [17:0] invert_table_q0;
wire    ap_block_pp0_stage0_11001;
reg   [16:0] r_V_reg_385;
reg   [16:0] r_V_1_reg_390;
wire  signed [25:0] sext_ln1273_fu_321_p1;
wire   [63:0] zext_ln255_fu_240_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln255_1_fu_271_p1;
wire   [63:0] zext_ln265_fu_316_p1;
wire  signed [15:0] icmp_ln1651_fu_102_p0;
wire  signed [15:0] icmp_ln1651_fu_102_p1;
wire   [0:0] icmp_ln1651_fu_102_p2;
wire   [0:0] xor_ln1651_fu_108_p2;
wire  signed [15:0] x_max_V_fu_114_p1;
wire  signed [15:0] x_max_V_fu_114_p2;
wire  signed [15:0] sext_ln1348_fu_122_p0;
wire   [15:0] x_max_V_fu_114_p3;
wire  signed [16:0] sext_ln1348_fu_122_p1;
wire  signed [16:0] sext_ln1348_1_fu_126_p1;
wire   [16:0] ret_V_fu_130_p2;
wire   [0:0] p_Result_8_fu_136_p3;
wire   [0:0] p_Result_9_fu_144_p3;
wire   [0:0] xor_ln895_fu_152_p2;
wire  signed [15:0] sext_ln1348_2_fu_170_p0;
wire  signed [16:0] sext_ln1348_2_fu_170_p1;
wire   [16:0] ret_V_1_fu_174_p2;
wire   [0:0] p_Result_10_fu_180_p3;
wire   [0:0] p_Result_11_fu_188_p3;
wire   [0:0] xor_ln895_1_fu_196_p2;
wire   [0:0] overflow_fu_158_p2;
wire   [0:0] xor_ln302_fu_164_p2;
wire   [9:0] select_ln346_fu_214_p3;
wire   [9:0] tmp_fu_222_p4;
wire   [9:0] p_Result_s_fu_232_p3;
wire   [0:0] overflow_1_fu_202_p2;
wire   [0:0] xor_ln302_1_fu_208_p2;
wire   [9:0] select_ln346_1_fu_245_p3;
wire   [9:0] tmp_1_fu_253_p4;
wire   [9:0] p_Result_5_fu_263_p3;
wire   [17:0] zext_ln813_fu_280_p1;
wire   [17:0] zext_ln346_fu_276_p1;
wire   [17:0] p_Val2_2_fu_284_p2;
wire   [0:0] p_Result_12_fu_290_p3;
wire   [9:0] tmp_2_fu_298_p4;
wire   [9:0] p_Result_7_fu_308_p3;
wire  signed [25:0] grp_fu_361_p2;
wire  signed [25:0] grp_fu_368_p2;
wire  signed [17:0] grp_fu_361_p0;
wire   [16:0] grp_fu_361_p1;
wire  signed [17:0] grp_fu_368_p0;
wire   [16:0] grp_fu_368_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [25:0] grp_fu_361_p10;
wire   [25:0] grp_fu_368_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

myproject_bincls_axilite_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_exp_table_ROM_Abkb #(
    .DataWidth( 17 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0),
    .ce0(exp_table_ce0),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1),
    .q1(exp_table_q1)
);

myproject_bincls_axilite_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s_invert_table_ROcud #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0),
    .q0(invert_table_q0)
);

myproject_bincls_axilite_mul_mul_18s_17ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 26 ))
mul_mul_18s_17ns_26_4_1_U278(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_361_p0),
    .din1(grp_fu_361_p1),
    .ce(1'b1),
    .dout(grp_fu_361_p2)
);

myproject_bincls_axilite_mul_mul_18s_17ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 26 ))
mul_mul_18s_17ns_26_4_1_U279(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_368_p0),
    .din1(grp_fu_368_p1),
    .ce(1'b1),
    .dout(grp_fu_368_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        r_V_1_reg_390 <= exp_table_q0;
        r_V_reg_385 <= exp_table_q1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce0 = 1'b1;
    end else begin
        exp_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exp_table_ce1 = 1'b1;
    end else begin
        exp_table_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        invert_table_ce0 = 1'b1;
    end else begin
        invert_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = {{grp_fu_361_p2[25:10]}};

assign ap_return_1 = {{grp_fu_368_p2[25:10]}};

assign exp_table_address0 = zext_ln255_1_fu_271_p1;

assign exp_table_address1 = zext_ln255_fu_240_p1;

assign grp_fu_361_p0 = sext_ln1273_fu_321_p1;

assign grp_fu_361_p1 = grp_fu_361_p10;

assign grp_fu_361_p10 = r_V_reg_385;

assign grp_fu_368_p0 = sext_ln1273_fu_321_p1;

assign grp_fu_368_p1 = grp_fu_368_p10;

assign grp_fu_368_p10 = r_V_1_reg_390;

assign icmp_ln1651_fu_102_p0 = p_read;

assign icmp_ln1651_fu_102_p1 = p_read1;

assign icmp_ln1651_fu_102_p2 = (($signed(icmp_ln1651_fu_102_p0) < $signed(icmp_ln1651_fu_102_p1)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln265_fu_316_p1;

assign overflow_1_fu_202_p2 = (xor_ln895_1_fu_196_p2 & p_Result_11_fu_188_p3);

assign overflow_fu_158_p2 = (xor_ln895_fu_152_p2 & p_Result_9_fu_144_p3);

assign p_Result_10_fu_180_p3 = ret_V_1_fu_174_p2[32'd16];

assign p_Result_11_fu_188_p3 = ret_V_1_fu_174_p2[32'd15];

assign p_Result_12_fu_290_p3 = p_Val2_2_fu_284_p2[32'd17];

assign p_Result_5_fu_263_p3 = ((xor_ln302_1_fu_208_p2[0:0] == 1'b1) ? select_ln346_1_fu_245_p3 : tmp_1_fu_253_p4);

assign p_Result_7_fu_308_p3 = ((p_Result_12_fu_290_p3[0:0] == 1'b1) ? 10'd511 : tmp_2_fu_298_p4);

assign p_Result_8_fu_136_p3 = ret_V_fu_130_p2[32'd16];

assign p_Result_9_fu_144_p3 = ret_V_fu_130_p2[32'd15];

assign p_Result_s_fu_232_p3 = ((xor_ln302_fu_164_p2[0:0] == 1'b1) ? select_ln346_fu_214_p3 : tmp_fu_222_p4);

assign p_Val2_2_fu_284_p2 = (zext_ln813_fu_280_p1 + zext_ln346_fu_276_p1);

assign ret_V_1_fu_174_p2 = ($signed(sext_ln1348_2_fu_170_p1) - $signed(sext_ln1348_1_fu_126_p1));

assign ret_V_fu_130_p2 = ($signed(sext_ln1348_fu_122_p1) - $signed(sext_ln1348_1_fu_126_p1));

assign select_ln346_1_fu_245_p3 = ((overflow_1_fu_202_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln346_fu_214_p3 = ((overflow_fu_158_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign sext_ln1273_fu_321_p1 = $signed(invert_table_q0);

assign sext_ln1348_1_fu_126_p1 = $signed(x_max_V_fu_114_p3);

assign sext_ln1348_2_fu_170_p0 = p_read1;

assign sext_ln1348_2_fu_170_p1 = sext_ln1348_2_fu_170_p0;

assign sext_ln1348_fu_122_p0 = p_read;

assign sext_ln1348_fu_122_p1 = sext_ln1348_fu_122_p0;

assign tmp_1_fu_253_p4 = {{ret_V_1_fu_174_p2[15:6]}};

assign tmp_2_fu_298_p4 = {{p_Val2_2_fu_284_p2[17:8]}};

assign tmp_fu_222_p4 = {{ret_V_fu_130_p2[15:6]}};

assign x_max_V_fu_114_p1 = p_read;

assign x_max_V_fu_114_p2 = p_read1;

assign x_max_V_fu_114_p3 = ((xor_ln1651_fu_108_p2[0:0] == 1'b1) ? x_max_V_fu_114_p1 : x_max_V_fu_114_p2);

assign xor_ln1651_fu_108_p2 = (icmp_ln1651_fu_102_p2 ^ 1'd1);

assign xor_ln302_1_fu_208_p2 = (p_Result_11_fu_188_p3 ^ p_Result_10_fu_180_p3);

assign xor_ln302_fu_164_p2 = (p_Result_9_fu_144_p3 ^ p_Result_8_fu_136_p3);

assign xor_ln895_1_fu_196_p2 = (p_Result_10_fu_180_p3 ^ 1'd1);

assign xor_ln895_fu_152_p2 = (p_Result_8_fu_136_p3 ^ 1'd1);

assign zext_ln255_1_fu_271_p1 = p_Result_5_fu_263_p3;

assign zext_ln255_fu_240_p1 = p_Result_s_fu_232_p3;

assign zext_ln265_fu_316_p1 = p_Result_7_fu_308_p3;

assign zext_ln346_fu_276_p1 = exp_table_q1;

assign zext_ln813_fu_280_p1 = exp_table_q0;

endmodule //myproject_bincls_axilite_softmax_stable_ap_fixed_ap_fixed_16_6_5_3_0_softmax_config7_s
